Task3 Абдуллаева Stack и Queue на массивах Object
MYORGSCHOOL/JavaSchool2023 pull request #101
Opened 2023-08-18 21:17 UTC by abdullaevavera

2023-08-19 14:30 UTC, IrinaKorsun requested changes

2023-08-19 14:30 UTC, IrinaKorsun commented on Task3/src/main/java/abdullaeva/Queue.java
> +        queueArray = new Object[maxSize];
this. к полям класса)

2023-08-19 14:30 UTC, IrinaKorsun commented on Task3/src/main/java/abdullaeva/Queue.java
> +    public final int SUCCESS = 1;
чтобы это прям были константы нужно сделать их статическими(

2023-08-19 14:30 UTC, IrinaKorsun commented on Task3/src/main/java/abdullaeva/Queue.java
> +                    builder.append(", ");
Хммммммм
Arrays.toString(this.queueArray)  глянь, может подойдет?

2023-08-19 14:30 UTC, IrinaKorsun commented on Task3/src/main/java/abdullaeva/Stack.java
> +            System.out.println("Ошибка вставки");
давай попробуем сделать стек расширяющимся? это нам пригодится в 4 задании)

2023-08-19 20:04 UTC, abdullaevavera commented on Task3/src/main/java/abdullaeva/Queue.java
> +                    builder.append(", ");
Он подходит, но выводит корявенько, если начало очереди лежит не по 0-му индексу в массиве. Если корявенький вывод подходит, могу через Arrays.toString реализовать. Поменять?

2023-08-19 20:10 UTC, abdullaevavera commented on Task3/src/main/java/abdullaeva/Queue.java
> +        queueArray = new Object[maxSize];
this использовать, даже если в конструкторе нет отвечающих им параметров? К массиву тоже this добавить? Запуталась маленько :(

2023-08-19 20:25 UTC, abdullaevavera commented on Task3/src/main/java/abdullaeva/Stack.java
> +            System.out.println("Ошибка вставки");
Сделать максимальный размер стэка Integer.MAX_VALUE - 1 и если в массиве больше нет места копировать в новый массив с увеличенным размером? А увеличивать размер массива как? По какой формуле?

2023-08-21 11:18 UTC, IrinaKorsun commented on Task3/src/main/java/abdullaeva/Queue.java
> +        queueArray = new Object[maxSize];
Ну ты же пишешь this.maxSize )

2023-08-21 11:19 UTC, IrinaKorsun commented on Task3/src/main/java/abdullaeva/Queue.java
> +                    builder.append(", ");
ок давай так оставим)

2023-08-21 11:19 UTC, IrinaKorsun commented on Task3/src/main/java/abdullaeva/Stack.java
> +            System.out.println("Ошибка вставки");
это твоя реализация) можешь на 2 умножать размер)

2023-08-22 18:12 UTC, markikz commented on Task3/src/main/java/abdullaeva/Queue.java
> +public class Queue {
На класс и поля было бы не плохо добавить доку

2023-08-22 18:18 UTC, markikz commented
билд упал, нужно ребейзнуться на актуальный мейн

2023-08-27 15:02 UTC, IrinaKorsun commented on Task3/src/main/java/abdullaeva/Stack.java
> +        if (top >= maxSize - 1) resizeArray();
давай тут потом на будущее будем добавлять фигурные скобки

2023-08-27 15:03 UTC, IrinaKorsun approved these changes

2023-08-27 15:03 UTC, merged