Task5 Позднякова Создание интерфейса Dictionary, его реализации и тестов
MYORGSCHOOL/JavaSchool2023 pull request #105
Opened 2023-08-20 18:09 UTC by Pozdnyakova-Elizaveta

2023-08-21 11:45 UTC, IrinaKorsun requested changes

2023-08-21 11:45 UTC, IrinaKorsun commented on Task5/src/main/java/pozdnyakova/DictionaryImplements.java
> +     * Метод для перестановки в массиве последнего элемента на место удаляемого элемента
у тебя написано что метод только в массиве что то делает, а по факту и в мапу тоже лезет
Давай либо манипуляции с мапой отсюда вынесем, либо метод переназовем)

2023-08-21 11:45 UTC, IrinaKorsun commented on Task5/src/main/java/pozdnyakova/DictionaryImplements.java
> +public class DictionaryImplements<G> implements Dictionary<G> {
Можно просто DictionaryImpl

2023-08-22 07:42 UTC, Pozdnyakova-Elizaveta commented on Task5/src/main/java/pozdnyakova/DictionaryImplements.java
> +     * Метод для перестановки в массиве последнего элемента на место удаляемого элемента
Перенесла действие с мапой в delete

2023-08-22 07:42 UTC, Pozdnyakova-Elizaveta commented on Task5/src/main/java/pozdnyakova/DictionaryImplements.java
> +public class DictionaryImplements<G> implements Dictionary<G> {
Переименовала

2023-08-22 09:50 UTC, IrinaKorsun approved these changes

2023-08-22 09:50 UTC, merged