Task5 Циммер Создание generic интерфейса и его реализация
MYORGSCHOOL/JavaSchool2023 pull request #110
Opened 2023-08-22 14:02 UTC by Julia-A-7

2023-08-22 18:04 UTC, markikz commented on Task5/src/test/java/tsimmer/DictionaryImplTest.java
> +    DictionaryImpl<Integer> dictionary = new DictionaryImpl<>();
private final

2023-08-22 18:07 UTC, markikz commented on Task5/src/main/java/tsimmer/DictionaryImpl.java
> +        if (consist(element)) {
if(!consist(element)){
 throw new DictionaryException("Такого элемента в справочнике нет");
}
дальше основной код без else, чтобы вложенности меньше было

2023-08-22 18:09 UTC, markikz commented on Task5/src/main/java/tsimmer/DictionaryImpl.java
> +
лишняя пустая строка

2023-08-22 18:10 UTC, markikz commented on Task5/src/main/java/tsimmer/DictionaryImpl.java
> +        if (!consist(element)) {
if (consist(element)) {
      ошибка
}
основной код

2023-08-24 14:20 UTC, IrinaKorsun requested changes

2023-08-24 14:20 UTC, IrinaKorsun commented on Task5/src/main/java/tsimmer/DictionaryImpl.java
> +        swap(array, index);
Это очень странно) ты сюда передаешь массив - поле класса, но в методе напрямую используешь мапу которая тоже поле)
Можешь передать только индекс, и давай метод назовем  changeElementIndex а то swap это всегда простая логика, что то поменяли и все, а тут ты в разные структуры ходишь внутри, сложный swap прям

2023-08-24 14:20 UTC, IrinaKorsun commented on Task5/src/test/java/tsimmer/DictionaryImplTest.java
> +    void testSuccessConsistElements() {
может неуспешные тесты тоже добавим? У тебя вон много исключений кидается в словаре

2023-08-27 03:01 UTC, IrinaKorsun approved these changes

2023-08-27 03:01 UTC, merged