Task1 Королев Добавление документации, сдача
MYORGSCHOOL/JavaSchool2023 pull request #111
Opened 2023-08-23 01:23 UTC by F1zon

2023-08-24 14:20 UTC, IrinaKorsun commented
Я конечно верю что хорошо работает) да вот только если мы такое вольем то у всех все сломается
Нужно чтобы сборка прошла

2023-08-24 14:23 UTC, IrinaKorsun requested changes

2023-08-24 14:23 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    private Map<Character, Double> coordinates = new TreeMap<>();
а для чего там treemap в векторе?

2023-08-24 14:23 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    double getY() {return coordinates.get('y');}
ctrl + alt + l

2023-08-24 14:23 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Task2.java
> +                // TODO: Векторное произведение
todo это недоделка, в чем тут туду заключается?

2023-08-24 14:23 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Method.java
> +    // [x]: Методы для суммы и разности
javadoc выгядит иначе

2023-08-24 14:23 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +        System.out.println("Ввекдите значение 1 вектора: ");
в задании про ввод вроде речи небыло..

2023-08-28 14:21 UTC, markikz commented
Все еще нужно поправить билд и название ПР Task2

2023-09-01 07:14 UTC, closed without merging