Task6 Проскурина Класс Config и класс для его заполнения через рефлексию
MYORGSCHOOL/JavaSchool2023 pull request #115
Opened 2023-08-23 15:40 UTC by OlgaProskurina

2023-08-24 14:41 UTC, IrinaKorsun requested changes

2023-08-24 14:41 UTC, IrinaKorsun commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +        throw new AssertionError("Нельзя создать экземпляр класса");
кажется этот код никто не сможет вызвать) кроме тебя самой

2023-08-24 14:41 UTC, IrinaKorsun commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +    public static void fromMap(Config dest, Map<? extends String, ?> src) {
? extends String
как будто не имеет смысла)
string это финальный класс и его даже никто не сможет расширить)

2023-08-24 14:41 UTC, IrinaKorsun commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +                field.set(dest, entry.getValue());
у тебя судя по типу параметра value может быть хоть что -  ?
А если там будет обьект? то как тогда отработает код?

2023-08-24 14:43 UTC, OlgaProskurina commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +    public static void fromMap(Config dest, Map<? extends String, ?> src) {
просто чтобы было понятно, что только для чтения

2023-08-24 14:46 UTC, OlgaProskurina commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +                field.set(dest, entry.getValue());
```java
@throws IllegalArgumentException            если {@code dest} равен {@code null}
     *                                             или {@code src} пуст,
     *                                             а также если тип присваемого значения
     *                                             не соответствует типу поля в {@code Config}
```
Там вылетит  IllegalArgumentException, если я правильно поняла о чем ты

2023-08-24 14:47 UTC, OlgaProskurina commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +        throw new AssertionError("Нельзя создать экземпляр класса");
Убрать?)

2023-08-24 14:50 UTC, OlgaProskurina commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +                field.set(dest, entry.getValue());
Но там по идее будет <? extends Object>, я, наверное, эксперименты свои не затерла

2023-08-24 14:55 UTC, OlgaProskurina commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +                field.set(dest, entry.getValue());
Получается так, я, видимо, эксперименты свои не затерла, сейчас поправлю

2023-08-25 09:35 UTC, IrinaKorsun commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +        throw new AssertionError("Нельзя создать экземпляр класса");
Можно исключение наверное убрать)

2023-08-25 09:38 UTC, IrinaKorsun commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +    public static void fromMap(Config dest, Map<? extends String, ?> src) {
Очень тонко... )) действительно, вижу такие примеры
<img width="859" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/ab6a4fe2-f5f0-4b62-8c13-950f9aff05d2">

2023-08-25 09:39 UTC, IrinaKorsun approved these changes

2023-08-25 09:43 UTC, IrinaKorsun requested changes

2023-08-25 09:43 UTC, IrinaKorsun commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +                field.set(dest, entry.getValue());
<img width="1327" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/afb28f0e-792f-4467-b7d4-d76476ad9f9a">

Я вот про это)
У нас поля ведь строковые, если мы делаем тип Object то тогда можем нарваться на ошибку

2023-08-27 03:54 UTC, IrinaKorsun commented on Task6/src/main/java/proskurina/ConfigLoader.java
> +                field.set(dest, entry.getValue());
ок поняла идею, давай так

2023-08-27 03:54 UTC, IrinaKorsun approved these changes

2023-08-27 03:55 UTC, merged