Task3 Алексенко Изменил классы Queue, Stack, StackTest
MYORGSCHOOL/JavaSchool2023 pull request #120
Opened 2023-08-25 21:28 UTC by 57nety

2023-08-27 15:27 UTC, IrinaKorsun requested changes

2023-08-27 15:27 UTC, IrinaKorsun commented on Task3/src/main/java/alexenko/Queue.java
> +    public void enqueue(Object o) throws RuntimeException{
давай alt + ctrl + l сделаем

2023-08-27 15:27 UTC, IrinaKorsun requested changes

2023-08-27 15:27 UTC, IrinaKorsun commented on Task3/src/test/java/alexenko/StackTest.java
> +
а точно нужно столько лишних пробелов?

2023-08-28 14:12 UTC, markikz commented on Task3/src/main/java/alexenko/Queue.java
> +    private final Object[] arr;
Нет смысла в сокращениях, лучше полностью array

2023-09-01 03:06 UTC, IrinaKorsun requested changes

2023-09-01 03:06 UTC, IrinaKorsun commented on Task3/src/main/java/alexenko/Queue.java
> +    private final int SIZE;
если пишешь SIZE то поле должно быть private static final int - константа

2023-09-01 03:06 UTC, IrinaKorsun commented on Task3/src/main/java/alexenko/Stack.java
> +    private static final int MAX_SIZE = Integer.MAX_VALUE;
вот тут норм как раз)

2023-09-01 03:07 UTC, IrinaKorsun requested changes

2023-09-01 03:07 UTC, IrinaKorsun commented on Task7/src/main/java/Task7.java
> +public class Task7 {
сделай ребейз на свежий мейн
Нужно чтобы тут небыло лишних изменений

2023-09-01 10:43 UTC, IrinaKorsun commented on Task7/src/main/java/Task7.java
> +public class Task7 {
Странно, как будто это я тебе сюда это подлила

2023-09-01 15:55 UTC, closed without merging