Task5 Пирязев Реализован интерфейс Dictionary и его имплементация
MYORGSCHOOL/JavaSchool2023 pull request #124
Opened 2023-08-28 08:15 UTC by Hippoflex

2023-08-28 14:09 UTC, markikz commented on Task5/src/main/java/piryazev/DictionaryImpl.java
> +    public void delete(G element) {
![image](https://github.com/MYORGSCHOOL/JavaSchool2023/assets/32810321/f13aac3a-4128-465d-8158-e6930dad05dc)
Что то не работает

2023-08-29 06:29 UTC, Hippoflex commented on Task5/src/test/java/piryazev/DictionaryImplTest.java
> +        for (int i = 0; i < 1_000_000; i++) {
вынес в константу

2023-08-29 06:29 UTC, Hippoflex commented on Task5/src/main/java/piryazev/DictionaryImpl.java
> +    public void delete(G element) {
пофиксил

2023-08-30 18:35 UTC, Hippoflex commented on Task5/src/test/java/piryazev/DictionaryImplTest.java
> +    @Timeout(value = EXECUTABLE_TIME, unit = TimeUnit.MILLISECONDS)
Мне самому отключить или Ира отключит при влитии?

2023-08-31 09:34 UTC, Hippoflex commented on Task5/src/test/java/piryazev/DictionaryImplTest.java
> +    @Timeout(value = EXECUTABLE_TIME, unit = TimeUnit.MILLISECONDS)
Тесты отключил

2023-09-01 03:10 UTC, IrinaKorsun requested changes

2023-09-01 03:10 UTC, IrinaKorsun commented on Task5/src/test/java/piryazev/DictionaryImplTest.java
> +        for (int i = 0; i < TEST_MILLION_ELEMENTS; i++) {
Получается у нас с тобой тесты не очень корректные, вроде как тест на удаление, а время и на вставку засекается

2023-09-01 03:10 UTC, IrinaKorsun commented on Task5/src/test/java/piryazev/DictionaryImplTest.java
> +            dictionary.insert(i);
Ты можешь вот этот инсерт вынести в  beforeAll например чтобы по умолчанию словарь был заполнен, а потом уже сделать тесты на удалени

2023-09-01 07:07 UTC, Hippoflex commented on Task5/src/test/java/piryazev/DictionaryImplTest.java
> +            dictionary.insert(i);
Сделал @BeforeAll

2023-09-02 12:38 UTC, IrinaKorsun approved these changes

2023-09-02 12:38 UTC, merged