Task6 Циммер реализация метода loadConfigFromMap
MYORGSCHOOL/JavaSchool2023 pull request #129
Opened 2023-08-29 09:52 UTC by Julia-A-7

2023-08-30 17:52 UTC, markikz commented on Task6/src/main/java/tsimmer/Config.java
> +    public String getApiKey() {
тут было бы не плохо отступить одну строчку

2023-08-30 17:53 UTC, markikz commented on Task6/src/main/java/tsimmer/Config.java
> +         @Override
ctr + alt + L

2023-09-01 03:18 UTC, IrinaKorsun requested changes

2023-09-01 03:18 UTC, IrinaKorsun commented on Task6/src/main/java/tsimmer/LoadConfigFromMap.java
> +            } catch (NoSuchFieldException e) {
Скорее интересно что исключение и перехватывается NoSuchFieldException
и выкидывается  throws NoSuchFieldException в сигнатуре метода, при этом у тебя вот эта строка

throw new NoSuchFieldException("Неправильное название поля!");
затирает исходный текст исключения что потом усложнит анализ ошибки)

давай выкидивать просто наверх NoSuchFieldException

2023-09-01 03:18 UTC, IrinaKorsun commented on Task6/src/test/java/tsimmer/ConfigTest.java
> +    @DisplayName("Тест успешного выполнения метода loadConfigFromMap")
если ты решишь исключение кидать то можно нужно тест на отлавливание исключения

2023-09-02 12:48 UTC, IrinaKorsun requested changes

2023-09-02 12:48 UTC, IrinaKorsun commented on Task6/src/main/java/tsimmer/LoadConfigFromMap.java
> +                throw new NoSuchFieldException(e.getMessage());
Но это ведь тоже самое что и просто в методе написать throws а тут не ловить)

2023-09-02 12:48 UTC, IrinaKorsun commented on Task6/src/main/java/tsimmer/LoadConfigFromMap.java
> +                throw new RuntimeException(e.getMessage());
А тут мы checked на unchecked меняем
Хммм ну гипотетически класс конфиг и его обработку ты пишешь и по идее это тебе нужно корректно все сделать чтобы ошибки нелегального доступа к полям небыло 
А программиста который твой код использует по идее не нужно заставлять нелегальный доступ обрабатывать 
Соглашусь..

2023-09-02 12:48 UTC, IrinaKorsun commented on Task6/src/main/java/tsimmer/LoadConfigFromMap.java
> +                throw new NoSuchFieldException(e.getMessage());
Давай вот эту ошибку просто не ловить а остальное ок)

2023-09-02 12:48 UTC, IrinaKorsun commented on Task6/src/main/java/tsimmer/Task6.java
> +        System.out.println(config);
Лишняя пустая строка)

2023-09-02 12:49 UTC, IrinaKorsun commented on Task6/src/test/java/tsimmer/ConfigTest.java
> +    }
Не хватает пустых строк между тестами

2023-09-02 12:49 UTC, IrinaKorsun commented on Task6/src/test/java/tsimmer/ConfigTest.java
> +    }
А тут лишняя пустая в конце)

2023-09-03 09:35 UTC, IrinaKorsun approved these changes

2023-09-03 09:35 UTC, merged