Task4 Абдуллаева RollbackStringBuilder с использованием собственного …
MYORGSCHOOL/JavaSchool2023 pull request #131
Opened 2023-08-31 20:31 UTC by abdullaevavera

…стэка + тесты

2023-09-01 03:23 UTC, IrinaKorsun requested changes

2023-09-01 03:23 UTC, IrinaKorsun commented on Task4/src/main/java/abdullaeva/RollbackStringBuilder.java
> +        this.stack = new Stack(15);
а стек ведь расширится если что?)
Если да то хорошо) а вот эту 15 можно вынести куда нибудь в константу наверх

2023-09-01 03:23 UTC, IrinaKorsun commented on Task4/src/main/java/abdullaeva/RollbackStringBuilder.java
> +        this.stack = new Stack(15);
В остальном все хорошо)

2023-09-01 06:09 UTC, markikz commented on Task4/src/main/java/abdullaeva/RollbackStringBuilder.java
> +        this.stack = new Stack(15);
все ок, мержим?

2023-09-01 12:29 UTC, abdullaevavera commented on Task4/src/main/java/abdullaeva/RollbackStringBuilder.java
> +        this.stack = new Stack(15);
Стэк расширяется, да. Просто конструктор с параметром начального размера оставила тогда :)

2023-09-02 12:50 UTC, IrinaKorsun requested changes

2023-09-02 12:50 UTC, IrinaKorsun commented on Task4/src/main/java/abdullaeva/RollbackStringBuilder.java
> +    private final static int size = 15;
SIZE ;)

2023-09-02 12:50 UTC, IrinaKorsun commented on Task4/src/main/java/abdullaeva/RollbackStringBuilder.java
> +    private final static int size = 15;
И мержим)

2023-09-03 07:28 UTC, abdullaevavera commented on Task4/src/main/java/abdullaeva/RollbackStringBuilder.java
> +    private final static int size = 15;
Готово, забыла про капслок для констант ><

2023-09-03 09:36 UTC, IrinaKorsun approved these changes

2023-09-03 09:36 UTC, merged