Task2 Королёв Исправление merge и документации.
MYORGSCHOOL/JavaSchool2023 pull request #132
Opened 2023-09-01 07:31 UTC by F1zon

Task2 Королёв Исправил merge, добавил документацию в method.java

2023-09-02 12:53 UTC, IrinaKorsun requested changes

2023-09-02 12:53 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +        System.out.print("Enter x: ");
Так… вектор не должен знать о том кто и как вводит координаты) ему они должны готовые передаваться )

2023-09-02 12:53 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    public String setString(Vector v) {
А почему метод называется setstring?  Он не принимает строку и не устанавливает ее никуда

2023-09-02 12:53 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    double getX() {return coordinates.get('x');}
Тут необходимо поправить форматирование

2023-09-02 12:53 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +public class Vector {
А для чего нам treemap?

2023-09-08 03:38 UTC, F1zon commented on Task2/src/main/java/koroliov/Vector.java
> +    double getX() {return coordinates.get('x');}
В плане? Сделать иной вывод?

2023-09-08 03:39 UTC, F1zon commented on Task2/src/main/java/koroliov/Vector.java
> +public class Vector {
Я сделал запись в treeMap("Строка X", сама координата).

2023-09-08 13:24 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    double getX() {return coordinates.get('x');}
Alt ctrl l

2023-09-13 04:46 UTC, closed without merging