Task7 Гроссу реализация аналога junit, аннотаций TestMethod, BeforeAl…
MYORGSCHOOL/JavaSchool2023 pull request #140
Opened 2023-09-03 13:00 UTC by GrossuEvgenia

…lMethod, AfterAllMethod и класса с тестами

2023-09-04 09:09 UTC, IrinaKorsun commented on Task7/src/main/java/grossu/Task7.java
> +import grossu.testexception.UncorrectedUseAnnotation;
Давай звездочку уберем

2023-09-04 09:09 UTC, IrinaKorsun commented on Task7/src/main/java/grossu/Task7.java
> +        }catch (UncorrectedUseAnnotation e){
Alt Ctrl l

2023-09-04 09:14 UTC, IrinaKorsun commented on Task7/src/main/java/grossu/TestRunner.java
> +        for (var m : methods) {
Может проще сделать фильтр?

2023-09-04 09:16 UTC, IrinaKorsun commented on Task7/src/main/java/grossu/TestRunner.java
> +        for (var m : methods) {
List<Method> beforeAllMethods = Arrays.stream(methods)
                 .filter(m -> m.isAnnotationPresent(BeforeAllMethod.class)).collect(Collectors.toList())

2023-09-04 09:16 UTC, IrinaKorsun commented on Task7/src/main/java/grossu/TestRunner.java
> +                .collect(Collectors.toCollection(ArrayList::new));
.collect(Collectors.toList())

2023-09-04 09:16 UTC, IrinaKorsun commented on Task7/src/main/java/grossu/testannotation/AfterAllMethod.java
> +import java.lang.annotation.*;
Звёздочка лишняя

2023-09-04 09:17 UTC, IrinaKorsun commented on Task7/src/main/java/grossu/testannotation/TestMethod.java
> +import java.lang.annotation.*;
Тоже)

2023-09-04 09:19 UTC, IrinaKorsun requested changes

2023-09-04 09:19 UTC, IrinaKorsun commented on Task7/src/main/java/grossu/testfortest/ClassWithTestMethodNoOrder.java
> +public class ClassWithTestMethodNoOrder {
Может это все в директорию с тестами положить ?

2023-09-04 09:50 UTC, GrossuEvgenia commented on Task7/src/main/java/grossu/testfortest/ClassWithTestMethodNoOrder.java
> +public class ClassWithTestMethodNoOrder {
класс Task7 тоже? иначе я не понимаю как обратится к классам из другого модуля?

2023-09-06 12:34 UTC, IrinaKorsun approved these changes

2023-09-06 12:34 UTC, merged