Task4 Алексенко Реализовал класс RollbackStringBuilder
MYORGSCHOOL/JavaSchool2023 pull request #143
Opened 2023-09-04 09:59 UTC by 57nety

2023-09-05 12:19 UTC, markikz commented on Task4/src/test/java/alexenko/RollbackStringBuilderTest.java
> +    public void insertStringIntoStringByIndex() {
Названия тестов лучше начитать со слова test. Например testSuccessInsert

2023-09-06 12:36 UTC, IrinaKorsun requested changes

2023-09-06 12:36 UTC, IrinaKorsun commented on Task4/build.gradle
>      testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
Для чего ?
Ещё и 2 раза)

2023-09-06 12:36 UTC, IrinaKorsun commented on Task4/src/main/java/alexenko/RollbackStringBuilder.java
> +        this.actions = new Stack(10);
10 в константу наверх

2023-09-08 13:28 UTC, IrinaKorsun approved these changes

2023-09-08 13:28 UTC, merged