Task6 Бабаджанов Реализовать метод для заполнения настроек из мапы
MYORGSCHOOL/JavaSchool2023 pull request #146
Opened 2023-09-04 20:32 UTC by bimaister

2023-09-05 12:50 UTC, markikz commented on Task6/src/main/java/babadzhanov/Config.java
> +    //Поля
Давай уберем такие комменты, вроде и так понятно, что это поля

2023-09-05 12:52 UTC, markikz commented on Task6/src/main/java/babadzhanov/DataLoader.java
> +                throw new RuntimeException(e.getMessage());
Давай лучше такой конструктор использовать, чтобы сохранилась информация о том какая ошибка была 
![image](https://github.com/MYORGSCHOOL/JavaSchool2023/assets/32810321/ecefb703-b97c-4428-9520-8d4e7feda170)

2023-09-05 17:58 UTC, bimaister commented on Task6/src/main/java/babadzhanov/Config.java
> +    //Поля
ага убрал)

2023-09-05 17:58 UTC, bimaister commented on Task6/src/main/java/babadzhanov/DataLoader.java
> +                throw new RuntimeException(e.getMessage());
поменял

2023-09-06 12:40 UTC, IrinaKorsun requested changes

2023-09-07 16:39 UTC, bimaister commented on Task6/src/main/java/babadzhanov/DataLoader.java
> +        for (K k : keySet) {
добавил)

2023-09-08 05:29 UTC, markikz commented on Task6/src/main/java/babadzhanov/DataLoader.java
> +        } else
Нужно else и if всегда использовать со скобочками {}, даже если одна строка. Визуально лучше воспринимается и если будет мерж конфлит меньше шансев поломки. И давай тут вообще уберем else, сделаем `if(object = null || map == null || map.isEmpty()){ throw RuntimeException} дальше основной код без else`

2023-09-08 07:48 UTC, bimaister commented on Task6/src/main/java/babadzhanov/DataLoader.java
> +        } else
ага поменял)

2023-09-08 13:30 UTC, IrinaKorsun approved these changes

2023-09-08 13:30 UTC, merged