Task7 Позднякова Создание тестовых аннотаций, класса для запуска тест…
MYORGSCHOOL/JavaSchool2023 pull request #151
Opened 2023-09-06 15:09 UTC by Pozdnyakova-Elizaveta

…ов и его тестирование

2023-09-08 13:42 UTC, IrinaKorsun requested changes

2023-09-08 13:42 UTC, IrinaKorsun commented on Task7/src/main/java/pozdnyakova/TestRun.java
> +        ArrayList<Method> methods = new ArrayList<Method>(Arrays.asList(testClass.getMethods()));
А тебе не хватит разве просто arrays.aslist() ? ) 
В твоём случае чтобы просто пройтись по списку совсем не обязательно именно в arraylist ещё упаковывать)

2023-09-08 13:42 UTC, IrinaKorsun commented on Task7/src/main/java/pozdnyakova/TestRun.java
> +                    if (testAnnotationPresence) {
Пока не поняла логику( что значит противоречащие в данной ситуации ?

2023-09-08 13:42 UTC, IrinaKorsun commented on Task7/src/main/java/pozdnyakova/TestRun.java
> +        if (!presenceTestMethod) {
Вот с этой строчки прям все классно, просто и понятно ) а вот выше код заставляет долго вчитываться ) 
А если взять один раз список методой  и запустить его в параметром в следующие методы :
1) List<> getBeforeAllAnnotated(ArrayList<Method> methods)
2) List<> getAfterAllAnnotated(ArrayList<Method> methods)
3) List<> getTestAnnotated(ArrayList<Method> methods)
потом их размеры проверить и пустить результат на invoke)
Кажется что тогда читаемость будет проще) и внутри методов можно фильтр через лямбду сделать

2023-09-08 13:42 UTC, IrinaKorsun commented on Task7/src/main/java/pozdnyakova/TestRun.java
> +        }
Давай тут либо выкидывать наверх либо обработаем)
Чтобы не просто зажевать и проглотить)

2023-09-08 13:44 UTC, IrinaKorsun requested changes

2023-09-08 13:44 UTC, IrinaKorsun commented on Task7/src/main/java/pozdnyakova/annotations/BeforeAllMethod.java
> +import java.lang.annotation.*;
Звездочки долой)

2023-09-08 13:44 UTC, IrinaKorsun commented on Task7/src/main/java/pozdnyakova/annotations/BeforeAllMethod.java
> +@Target({ElementType.ANNOTATION_TYPE, ElementType.METHOD})
Я думаю target method достаточно

2023-09-08 13:44 UTC, IrinaKorsun commented on Task7/src/main/java/pozdnyakova/annotations/TestMethod.java
> +import java.lang.annotation.*;
Аналогично )

2023-09-08 13:44 UTC, IrinaKorsun commented on Task7/src/main/java/pozdnyakova/exception/ConflictingAnnotationsException.java
> +
Alt ctrl L

2023-09-08 13:44 UTC, IrinaKorsun commented on Task7/src/test/java/pozdnyakova/TestRunTest.java
> +import pozdnyakova.testClasses.*;
Аналогично )

2023-09-09 13:29 UTC, Pozdnyakova-Elizaveta commented on Task7/src/main/java/pozdnyakova/TestRun.java
> +        if (!presenceTestMethod) {
Исправила с добавлением этих методов

2023-09-09 13:29 UTC, Pozdnyakova-Elizaveta commented on Task7/src/main/java/pozdnyakova/TestRun.java
> +        }
Выкинула наверх

2023-09-09 13:29 UTC, Pozdnyakova-Elizaveta commented on Task7/src/main/java/pozdnyakova/annotations/BeforeAllMethod.java
> +import java.lang.annotation.*;
Заменила все звездочки

2023-09-09 13:31 UTC, Pozdnyakova-Elizaveta commented on Task7/src/main/java/pozdnyakova/TestRun.java
> +                    if (testAnnotationPresence) {
В новых методах оставила выкидывание исключения, если есть методы одновременно с BeforeAllMethod и TestMethod или с AfterAllMethod и TestMethod

2023-09-10 03:28 UTC, IrinaKorsun approved these changes

2023-09-10 03:29 UTC, merged