Task5. Grankin. Задача из яндекса.
MYORGSCHOOL/JavaSchool2023 pull request #153
Opened 2023-09-07 14:28 UTC by AlexGr5

Реализация словаря с условиями из яндекса

2023-09-08 05:33 UTC, markikz commented on Task5/src/main/java/grankin/DictionaryImpl.java
> +            while (arrayList.get(index) == null) {
Не уловил зачем нужен while, кажется с ним не будет O(1)

2023-09-08 05:35 UTC, markikz commented on Task5/src/main/java/grankin/DictionaryImpl.java
> +                G tmp = arrayList.get(index);
давай для переменной tmp более осмысленное название сделаем

2023-09-08 05:37 UTC, markikz commented on Task5/src/main/java/grankin/DictionaryImpl.java
> +            if (index < arrayList.size() - 1) {
правильно понял, что проверка нужна, если элемент уже последний?

2023-09-08 12:35 UTC, AlexGr5 commented on Task5/src/main/java/grankin/DictionaryImpl.java
> +            while (arrayList.get(index) == null) {
На всякий случай, вдруг ячейка пустая, тогда нужно заново найти случайное число.

2023-09-08 12:43 UTC, AlexGr5 commented on Task5/src/main/java/grankin/DictionaryImpl.java
> +            if (index < arrayList.size() - 1) {
Если удаляемый элемент не последний, то переставляем его на последнее место, иначе ничего не переставляем. Удаляем выбранный элемент.
(размер списка должен уменьшится и значений null не будет в списке и while из getRandom не будет заходить ни разу, но он там есть на всякий случай, вдруг что-то не удалится)

2023-09-08 13:50 UTC, IrinaKorsun commented on Task5/src/main/java/grankin/Dictionary.java
> +    G getRandom();
Давай добавим переводы строк и доку

2023-09-08 13:52 UTC, IrinaKorsun commented on Task5/src/main/java/grankin/DictionaryImpl.java
> +            if (index < arrayList.size() - 1) {
Логика « вдруг что то не удалится» это прям плоховатые логика ) это из разряда Вдруг мой код не будет работать )
Потом реализуемые методы будут гораздо сложнее и если мы на каждый чих будем перестраховываться то потом будем седыми и нервными если станем такой код разбирать )

2023-09-08 13:55 UTC, IrinaKorsun requested changes

2023-09-08 13:55 UTC, IrinaKorsun commented on Task5/src/main/java/grankin/DictionaryImpl.java
> +            result = true;
А может просто return hashmap.contains() ?

2023-09-08 13:55 UTC, IrinaKorsun commented on Task5/src/main/java/grankin/Task5.java
> +            //System.out.println(dictionary.getRandom());
Давай мёртвый код поубираем)

2023-09-10 14:41 UTC, IrinaKorsun requested changes

2023-09-10 14:41 UTC, IrinaKorsun commented on Task5/src/main/java/grankin/DictionaryImpl.java
> +            //while (arrayList.get(index) == null) {
Ещё мёртвый код?

2023-09-10 14:41 UTC, IrinaKorsun commented
Больше нет вопросов

2023-09-11 14:53 UTC, markikz commented on Task5/src/main/java/grankin/DictionaryImpl.java
> +            //while (arrayList.get(index) == null) {
он же больше не нужен, нужно удалить

2023-09-13 21:50 UTC, markikz approved these changes

2023-09-13 21:55 UTC, markikz commented on Task5/src/main/java/grankin/DictionaryImpl.java
> +        return hashMap.get(element) != null;
В маппе есть такой метод на этот случай
![image](https://github.com/MYORGSCHOOL/JavaSchool2023/assets/32810321/518be26c-a56f-4b1e-88e8-26cdbe081b96)

2023-09-14 08:30 UTC, IrinaKorsun approved these changes

2023-09-14 08:30 UTC, merged