Task5 Алексенко Реализовал интерфейс Dictionary, и класс DictionaryImpl
MYORGSCHOOL/JavaSchool2023 pull request #155
Opened 2023-09-08 00:18 UTC by 57nety

2023-09-08 14:01 UTC, IrinaKorsun requested changes

2023-09-08 14:01 UTC, IrinaKorsun commented on Task5/src/main/java/alexenko/DictionaryImpl.java
> +        K extremeElement = list.get(list.size()-1);
Ну это ведь не совсем swap… это поставить элемент из конца куда то в середину)

2023-09-08 14:01 UTC, IrinaKorsun commented on Task5/src/main/java/alexenko/DictionaryImpl.java
> +        K extremeElement = list.get(list.size()-1);
Экстремальный элемент ?)

2023-09-10 14:39 UTC, IrinaKorsun requested changes

2023-09-10 14:39 UTC, IrinaKorsun commented on Task5/src/main/java/alexenko/DictionaryImpl.java
> +    public void insert(K element) {
У тебя я смотрю метод под это прям выделен) лучше тогда им воспользоваться чтобы одинаково было

2023-09-10 14:39 UTC, IrinaKorsun commented on Task5/src/main/java/alexenko/Dictionary.java
> +public interface Dictionary<G>{
Alt ctrl l

2023-09-10 14:39 UTC, IrinaKorsun commented
Больше нет вопросов

2023-09-19 03:49 UTC, 57nety commented on Task5/src/main/java/alexenko/DictionaryImpl.java
> +    public void insert(K element) {
Что-то я не понял, что вы имеете ввиду :(

2023-09-19 09:51 UTC, IrinaKorsun approved these changes

2023-09-19 09:52 UTC, IrinaKorsun commented on Task5/src/main/java/alexenko/DictionaryImpl.java
> +    public void insert(K element) {
У тебя есть метод consist с той же логикой)

2023-09-19 09:52 UTC, merged