Task6 Савинский Reflection API
MYORGSCHOOL/JavaSchool2023 pull request #159
Opened 2023-09-10 05:38 UTC by rigastalin

Task6 Савинский Reflection API

2023-09-10 14:54 UTC, IrinaKorsun requested changes

2023-09-10 14:54 UTC, IrinaKorsun commented on Task6/src/main/java/savinskiy/Config.java
> +        for (var entry : configMap.entrySet()) {
Если configmap == null то будет npe

2023-09-10 14:54 UTC, IrinaKorsun commented on Task6/src/main/java/savinskiy/Config.java
> +                field.setAccessible(true);
Содержание класса config может быть абсолютно любым 
В задании указан только пример 
Для чего мы ниже проверяем принадлежность к типу ?

2023-09-12 14:36 UTC, rigastalin commented on Task6/src/main/java/savinskiy/Config.java
> +        for (var entry : configMap.entrySet()) {
Добавил проверку на null

2023-09-12 14:36 UTC, rigastalin commented on Task6/src/main/java/savinskiy/Config.java
> +                field.setAccessible(true);
Поменял на любое содержание

2023-09-13 21:45 UTC, markikz approved these changes

2023-09-14 08:28 UTC, IrinaKorsun approved these changes

2023-09-14 08:29 UTC, merged