Task5 Малахова Реализован класс DictionaryImpl
MYORGSCHOOL/JavaSchool2023 pull request #161
Opened 2023-09-10 10:11 UTC by Ulyana-Malakhova

2023-09-10 14:58 UTC, IrinaKorsun requested changes

2023-09-10 14:58 UTC, IrinaKorsun commented on Task5/src/main/java/malakhova/Dictionary.java
> +    G getRandom();
Давай сюда доку добавим

2023-09-10 14:58 UTC, IrinaKorsun commented on Task5/src/main/java/malakhova/Dictionary.java
> +    G getRandom();
Краткую

2023-09-10 14:58 UTC, IrinaKorsun commented on Task5/src/main/java/malakhova/DictionaryImpl.java
> +        arrayList.remove(arrayList.size() - 1);
Теперь у нас название метода не совпадает с его действиями 
Вроде предполагается просто замена мест а тут вдруг ещё удаление появляется

2023-09-10 14:58 UTC, IrinaKorsun commented on Task5/src/test/java/malakhova/DictionaryImplTest.java
> +    private static final long TIME_TEST = 100;
Сервера слабенькие… давай время увеличим чтобы тут проверки не падали)

2023-09-11 15:33 UTC, Ulyana-Malakhova commented on Task5/src/main/java/malakhova/Dictionary.java
> +    G getRandom();
Добавила

2023-09-11 15:34 UTC, Ulyana-Malakhova commented on Task5/src/main/java/malakhova/DictionaryImpl.java
> +        arrayList.remove(arrayList.size() - 1);
Поменяла название метода

2023-09-11 15:35 UTC, Ulyana-Malakhova commented on Task5/src/test/java/malakhova/DictionaryImplTest.java
> +    private static final long TIME_TEST = 100;
Увеличила TIME_TEST и количество элементов в словаре

2023-09-11 17:32 UTC, markikz approved these changes

2023-09-11 17:35 UTC, markikz submitted a review, later dismissed

2023-09-11 17:35 UTC, markikz commented on Task5/src/main/java/malakhova/DictionaryImpl.java
> +        arrayList.remove(arrayList.size() - 1);
Еще актуально в доке и названии поменять местами, а по факту еще удаление )

2023-09-12 02:49 UTC, Ulyana-Malakhova commented on Task5/src/main/java/malakhova/DictionaryImpl.java
> +        arrayList.remove(arrayList.size() - 1);
Поменяла название и дополнила документацию

2023-09-12 05:26 UTC, IrinaKorsun approved these changes

2023-09-12 05:27 UTC, IrinaKorsun approved these changes

2023-09-12 05:28 UTC, merged