Task2 Королёв Исправли коменты
MYORGSCHOOL/JavaSchool2023 pull request #168
Opened 2023-09-14 03:37 UTC by F1zon

Пересоздал ветку, что то не получалось у меня схлопнуть коммиты, исправил коменты и убрал TODO

2023-09-14 03:40 UTC, F1zon commented
Так же сделал Конструктор Vector публичным, для доступа к нему из других пакетов.

2023-09-14 08:28 UTC, IrinaKorsun requested changes

2023-09-14 08:28 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +     */
Смотри, у тебя по факту метод ничего не сетит, то есть в поля значения не присваивает 
Он только генерирует и возвращает список
Это должен быть метод с названием get

2023-09-14 08:28 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +        String one = String.format("%.3f", v.getX());
Аналогично, метод никому ничего не присваивает

2023-09-14 08:28 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    public String setString(String X, String Y, String Z)  {
Этот метод наверное не должен быть публичным? Он используется только в рамках этого класса ?

2023-09-14 08:28 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    double getX() {return coordinates.get('x');}
Тут не хватает модификатора доступа

2023-09-14 08:28 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    double getY() {return coordinates.get('y');}
Аналогично

2023-09-14 08:28 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Method.java
> +    String vectorProduct(Vector v1, Vector v2) {
Кажется что эти методы тоже должны выть в классе вектор

2023-09-19 09:57 UTC, IrinaKorsun requested changes

2023-09-19 09:57 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +     */
По математике сумма векторов это вектор

2023-09-19 09:57 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    String difference(Vector v1, Vector v2) {
Разность векторов это вектор)

2023-09-19 09:57 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    public String convertString(String X, String Y, String Z)  {
А это вынести в переопределенный метод toString класса вектор

2023-09-19 09:59 UTC, IrinaKorsun requested changes

2023-09-19 09:59 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +     */
Векторное произведение это тоже вектор

2023-09-19 09:59 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> + /**
Тут не хватает alt ctrl l

2023-09-19 09:59 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    private static Vector vectorGeneration() {
Приватные методы вниз, публичные наверх

2023-09-20 20:47 UTC, markikz commented on Task2/src/main/java/koroliov/Vector.java
> +    public String getString(Vector v) {
название toString больше подходит

2023-09-20 20:49 UTC, markikz commented on Task2/src/main/java/koroliov/Vector.java
> +public class Vector {
было бы не плохо добавить доку на класс

2023-09-20 20:49 UTC, markikz commented on Task2/src/main/java/koroliov/Vector.java
> +    private static Vector vectorGeneration() {
актуально

2023-09-20 20:50 UTC, markikz commented on Task2/src/main/java/koroliov/Vector.java
> +    double lengthVector(Vector vector) {
во втором задании вроде можно не использовать модификаторы доступа, но лучше добавить public, чтобы из других пакетов метод был доступен

2023-09-24 14:02 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    public String convertString(String X, String Y, String Z)  {
Актуально

2023-09-25 03:25 UTC, F1zon commented on Task2/src/main/java/koroliov/Vector.java
> +    private static Vector vectorGeneration() {
private Map<Character, Double> Тоже вниз или можно оставить сверху?

2023-09-26 15:11 UTC, IrinaKorsun approved these changes

2023-09-26 15:12 UTC, IrinaKorsun commented on Task2/src/main/java/koroliov/Vector.java
> +    private static Vector vectorGeneration() {
Все приватное конечно вниз)

2023-09-26 15:13 UTC, IrinaKorsun commented
В пр есть лишние удаления классов

2023-10-04 14:32 UTC, IrinaKorsun approved these changes

2023-10-04 14:32 UTC, merged