Task7 Бабаджанов Написать свой тестовый фреймворк
MYORGSCHOOL/JavaSchool2023 pull request #169
Opened 2023-09-14 23:20 UTC by bimaister

2023-09-15 13:49 UTC, IrinaKorsun requested changes

2023-09-15 13:49 UTC, IrinaKorsun commented on Task7/src/main/java/babadzhanov/TestFramework.java
> +        final Object testObject = testClass.getDeclaredConstructor().newInstance();
Проверить что переданный аргумент не пустой)

2023-09-15 13:49 UTC, IrinaKorsun commented on Task7/src/main/java/babadzhanov/TestFramework.java
> +            if (beforeMethod.isAnnotationPresent(annotation)) {
Это ведь у нас не beforemethod) это может быть и after
Можно назвать annotatedMethod

2023-09-16 13:02 UTC, bimaister commented on Task7/src/main/java/babadzhanov/TestFramework.java
> +        final Object testObject = testClass.getDeclaredConstructor().newInstance();
это над на монитор повесить) постоянно забываю. Спс)

2023-09-16 13:05 UTC, bimaister commented on Task7/src/main/java/babadzhanov/TestFramework.java
> +            if (beforeMethod.isAnnotationPresent(annotation)) {
ага точно, прост изначально было два отдельных метода для поиска аннотаций before/after, потом эт переросло в один метод с передаваемым параметром)) А переменная в цикле досталась по наследству)))) Исправил

2023-09-17 10:44 UTC, IrinaKorsun approved these changes

2023-09-17 10:44 UTC, merged