Task6 Воловник Reflection API
MYORGSCHOOL/JavaSchool2023 pull request #180
Opened 2023-09-26 07:19 UTC by alex65677

2023-09-26 14:59 UTC, IrinaKorsun requested changes

2023-09-26 14:59 UTC, IrinaKorsun commented on Task6/src/main/java/volovnik/Task6.java
> +            for (Map.Entry<String, Object> entry : configMap.entrySet()) {
Давай сделаем проверку на дурака
Что переданные параметры не пустые

2023-09-26 14:59 UTC, IrinaKorsun commented on Task6/src/main/java/volovnik/Task6.java
> +        } catch (NoSuchFieldException | IllegalAccessException e) {
Вот тут можно ещё описание ошибки добавить

2023-09-26 14:59 UTC, IrinaKorsun commented on Task6/src/main/java/volovnik/Task6.java
> +
Лучше кстати сделать чтобы метод возвращал Config и внутри создавал екземпляр его класса 
Чтобы в методе мейн не приходилось это делать

2023-09-27 12:14 UTC, alex65677 commented on Task6/src/main/java/volovnik/Task6.java
> +            for (Map.Entry<String, Object> entry : configMap.entrySet()) {
Сделал

2023-09-27 12:14 UTC, alex65677 commented on Task6/src/main/java/volovnik/Task6.java
> +        } catch (NoSuchFieldException | IllegalAccessException e) {
Добавил

2023-09-27 12:15 UTC, alex65677 commented on Task6/src/main/java/volovnik/Task6.java
> +
Сделал

2023-09-27 14:50 UTC, IrinaKorsun commented on Task6/src/main/java/volovnik/Task6.java
> +            throw new IncorrectConfigFieldException("Неверно заданы параметры конфигурации");
Я бы ещё саму ошибку выкинула, это на будущее а то по такой сейчас причину ошибки тяжело будет понять

2023-09-27 14:50 UTC, IrinaKorsun commented on Task6/src/main/java/volovnik/Task6.java
> +            throw new IncorrectConfigFieldException("Неверно заданы параметры конфигурации");
А лучше на каждый тип ошибки прям корректный текст выводить, что да почему

2023-09-27 14:51 UTC, IrinaKorsun approved these changes

2023-09-27 14:51 UTC, merged