Task7. Grankin. Свой класс с аннотациями тестирования.
MYORGSCHOOL/JavaSchool2023 pull request #181
Opened 2023-09-26 08:52 UTC by AlexGr5

Класс с аннотациями для тестирования методов.

2023-09-26 15:09 UTC, IrinaKorsun requested changes

2023-09-26 15:09 UTC, IrinaKorsun commented on Task7/src/main/java/grankin/AfterAllMethod.java
> +import java.lang.annotation.*;
Звездочки долой)

2023-09-26 15:09 UTC, IrinaKorsun commented on Task7/src/main/java/grankin/ForTestingAnotherClass.java
> +            if (information.getCountAfterAllMethod() > 1 || information.getCountBeforeAllMethod() > 1) {
Мёртвый код долой)

2023-09-26 15:09 UTC, IrinaKorsun commented on Task7/src/main/java/grankin/ForTestingAnotherClass.java
> +
Давай ещё лишние пробелы уберем

2023-09-26 15:09 UTC, IrinaKorsun commented on Task7/src/main/java/grankin/ForTestingAnotherClass.java
> +        try {
А если переданное имя класса пустое ?

2023-09-26 15:09 UTC, IrinaKorsun commented on Task7/src/main/java/grankin/ForTestingAnotherClass.java
> +                    information.getPrioritetiTestMethod());                     // Сортируем массив методо по приоритету из аннотации @TestMethod
Priopiteti?)

2023-09-26 15:09 UTC, IrinaKorsun commented on Task7/src/main/java/grankin/ForTestingAnotherClass.java
> +            throw new RuntimeException(e);
Сейчас у нас путь обработки всех исключений одинаковая, просто кинуть рантайм 
Давай может текст ошибки ещё кинем ?

2023-09-26 15:09 UTC, IrinaKorsun commented on Task7/src/main/java/grankin/InformationOfMethods.java
> +    private List<Integer> prioritetiTestMethod = new ArrayList<>();
А если тут хранить не индексы и приоритеты, а сразу методы ?

2023-09-26 15:09 UTC, IrinaKorsun commented on Task7/src/main/java/grankin/ForTestingAnotherClass.java
> +        // Сортровка сравнением
Collections.sort?)

2023-09-30 15:42 UTC, AlexGr5 commented on Task7/src/main/java/grankin/InformationOfMethods.java
> +    private List<Integer> prioritetiTestMethod = new ArrayList<>();
Я захотел так реализовать

2023-09-30 16:05 UTC, AlexGr5 commented on Task7/src/main/java/grankin/ForTestingAnotherClass.java
> +        // Сортровка сравнением
В данной ситуации мне хотелось самому сортировать

2023-09-30 16:17 UTC, AlexGr5 commented on Task7/src/main/java/grankin/AfterAllMethod.java
> +import java.lang.annotation.*;
Это идея сама что-то делает, но хорошо, я уберу

2023-09-30 16:32 UTC, AlexGr5 commented on Task7/src/main/java/grankin/InformationOfMethods.java
> +     */
Типа объявить класс внутри другого класса? Если честно, то я такое не люблю, выглядит отвратительно.

2023-09-30 16:33 UTC, AlexGr5 commented on Task7/src/main/java/grankin/ForTestingAnotherClass.java
> +                    information.getPrioritetiTestMethod());                     // Сортируем массив методо по приоритету из аннотации @TestMethod
Prioriteti (приоритеты), типа транскрипция или что-то похожее

2023-09-30 16:41 UTC, AlexGr5 commented on Task7/src/main/java/grankin/InformationOfMethods.java
> +    private List<Integer> prioritetiTestMethod = new ArrayList<>();
Мне просто больше приятнее с индексами работать

2023-10-02 16:11 UTC, IrinaKorsun commented on Task7/src/main/java/grankin/BeforeAllMethod.java
> +import java.lang.annotation.*;
еще осталось)
А ты настрой идею)
<img width="1034" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/89b0bdbf-e45d-460e-9cb5-61f48215822b">

2023-10-02 18:14 UTC, AlexGr5 commented on Task7/src/main/java/grankin/BeforeAllMethod.java
> +import java.lang.annotation.*;
Точно, я забыл, это же было в одной из первых лекций...

2023-10-03 17:08 UTC, markikz commented on Task7/src/main/java/grankin/AfterAllMethod.java
> +import java.lang.annotation.*;
чтобы идея не схлопывала импорты 
![image](https://github.com/MYORGSCHOOL/JavaSchool2023/assets/32810321/63be3abd-6e6b-4a7c-a161-691985346378)

2023-10-03 17:11 UTC, markikz commented on Task7/src/main/java/druzhinin/exceptions/FailedTestClassInstantiatingException.java
> + * Nсключение для индикации ошибки создания экземпляра тестового класса.
может вернем как было?

2023-10-03 17:13 UTC, markikz commented on Task7/src/main/java/grankin/ExampleClassWithAnnotations.java
> +    public static void Befor() {
название методов всегда с маленькой буквы

2023-10-04 12:35 UTC, AlexGr5 commented on Task7/src/main/java/druzhinin/exceptions/FailedTestClassInstantiatingException.java
> + * Nсключение для индикации ошибки создания экземпляра тестового класса.
Да я не специально, я же говорил, что у меня по какой-то причине не работает русская буква И, компиляция из-за этого не проходит, хоть это и комментарии, причем даже на какой-то чужой проект, у себя я вообще перестал букву И писать.

2023-10-04 12:40 UTC, AlexGr5 commented on Task7/src/main/java/druzhinin/exceptions/FailedTestClassInstantiatingException.java
> + * Nсключение для индикации ошибки создания экземпляра тестового класса.
Что-то с кодировками было, вроде поправил

2023-10-04 14:35 UTC, IrinaKorsun approved these changes

2023-10-04 14:35 UTC, merged