Task9 Гроссу Реализация Client и Server
MYORGSCHOOL/JavaSchool2023 pull request #184
Opened 2023-09-27 18:32 UTC by GrossuEvgenia

2023-09-28 18:23 UTC, markikz commented on Task9/src/main/java/grossu/Client.java
> +    static class ThreadInput implements Runnable {
Давай сделаем 2 пакета client, server и все классы разнесем по собственным файлам

2023-09-28 18:23 UTC, markikz commented on Task9/src/main/java/grossu/Server.java
> +
лишняя строка

2023-09-28 18:25 UTC, markikz commented on Task9/src/main/java/grossu/ThreadSocket.java
> +
строка

2023-09-28 18:33 UTC, markikz commented on Task8/src/main/java/Main.java
> -package org.example;
кажется это не нужно удалять

2023-09-29 05:20 UTC, GrossuEvgenia commented on Task8/src/main/java/Main.java
> -package org.example;
не совсем понимаю, что нужно делать , восстановить этот файл? это просто пакет, который был при дефолтном создании модуля для 8 таски

2023-09-29 05:21 UTC, GrossuEvgenia commented on Task8/src/main/java/Main.java
> -package org.example;
остальные замечания исправила

2023-09-30 09:08 UTC, IrinaKorsun requested changes

2023-09-30 09:08 UTC, IrinaKorsun commented on Task9/src/main/java/grossu/server/UserListSingleton.java
> +    public void login(String username, Socket socket) {
А если прям удалить прям клиента из списка если он отключился? Как будто смысл тот же останется а доп логики меньше будет в коде

2023-09-30 09:08 UTC, IrinaKorsun commented on Task9/src/main/java/grossu/server/ThreadSocket.java
> +    private synchronized void setStateOffline() {
давай еще все приватное вниз кинем а публичное наверху оставим

2023-09-30 10:10 UTC, IrinaKorsun commented on Task9/src/main/java/grossu/server/ThreadSocket.java
> +                        OutputStreamWriter writeMessage = findUser(user);
предлагаю это написать в обертке  trywithresources так как по идее после отправки сообщения клиенту мы должны закрыть поток на запись

2023-09-30 10:10 UTC, IrinaKorsun commented on Task9/src/main/java/grossu/server/ThreadSocket.java
> +
и тут лишние пробелы остались

2023-09-30 10:11 UTC, IrinaKorsun commented on Task9/src/main/java/grossu/server/ThreadSocket.java
> +                        OutputStreamWriter writeMessage = findUser(user);
а, отбой... вижу что тут это не подойдет

2023-10-02 16:13 UTC, IrinaKorsun approved these changes

2023-10-02 16:14 UTC, merged