Task7 Алексенко Реализовал аннотации и класс для запуска тестов
MYORGSCHOOL/JavaSchool2023 pull request #189
Opened 2023-10-03 23:29 UTC by 57nety

2023-10-04 14:45 UTC, IrinaKorsun requested changes

2023-10-04 14:45 UTC, IrinaKorsun commented on Task7/src/main/java/alexenko/TestStarter.java
> +            Object objectAnyClass = anyClass.getConstructor().newInstance();
Npe проверку бы сюда]

2023-10-04 14:45 UTC, IrinaKorsun commented on Task7/src/main/java/alexenko/TestStarter.java
> +                    if (countAnnotationsOnMethod > MAX_COUNT_ANNOTATIONS_ON_METHOD) {
Упадёт исключение но не поймём почему ) давай ещё вместе с самим обьектом throwable передадим текст почему упало)

2023-10-04 14:45 UTC, IrinaKorsun commented on Task7/src/main/java/alexenko/TestStarter.java
> +                    if (countAnnotationsOnMethod > MAX_COUNT_ANNOTATIONS_ON_METHOD) {
Если я не ошибаюсь можно же просто size у массива чекнуть?)

2023-10-04 14:45 UTC, IrinaKorsun commented on Task7/src/main/java/alexenko/annotations/TestMethod.java
> +
Предлагаю настроить идею чтобы она не генерила звездочек

2023-10-04 14:45 UTC, IrinaKorsun commented on Task7/src/main/java/alexenko/exceptions/ClassTestNotHaveAnnotationsTestMethodException.java
> +public class ClassTestNotHaveAnnotationsTestMethodException extends RuntimeException{
Alt ctrl l

2023-10-04 14:45 UTC, IrinaKorsun commented on Task7/src/main/java/alexenko/exceptions/IllegalArgumentInAnnotationTestMethodException.java
> +
Alt ctrl l

2023-10-04 22:12 UTC, 57nety commented on Task7/src/main/java/alexenko/TestStarter.java
> +                    if (countAnnotationsOnMethod > MAX_COUNT_ANNOTATIONS_ON_METHOD) {
В этой реализации, я допускаю что над методом могут быть ещё какие-то аннотации, но именно мои должны быть в единственном числе

2023-10-07 08:28 UTC, markikz commented on Task7/src/main/java/alexenko/exceptions/ObjectTypeClassIsNullValue.java
> +        super();
текст не передается

2023-10-07 08:42 UTC, markikz commented on Task7/src/main/java/alexenko/TestStarter.java
> +                            throw new IllegalArgumentInAnnotationTestMethodException();
Проверки на число аннотаций не рабочие. Вынеси их за цикл и убери счетчик

2023-10-07 21:35 UTC, 57nety commented on Task7/src/main/java/alexenko/TestStarter.java
> +                            throw new IllegalArgumentInAnnotationTestMethodException();
О какой не работоспособности вы говорите? Я только что проверил, когда над методом более одной моей аннотации, например, @AfterAllMethods и сразу же @BeforeAllMethods, то выбрасывается исключение. Этот счётчик считает не все аннотации, а только те, которые реализовал я. Задумано, что в классе тесте, нельзя использовать более одной моей аннотации на одном методе. Это не правильно?

2023-10-11 01:51 UTC, IrinaKorsun commented on Task7/src/main/java/alexenko/TestStarter.java
> +                            throw new IllegalArgumentInAnnotationTestMethodException();
Да,в логике тут теперь нет противоречий

2023-10-11 01:51 UTC, IrinaKorsun approved these changes

2023-10-11 01:51 UTC, merged