Task9 Янько Созданы классы для осуществления взаимодействия клиента и…
MYORGSCHOOL/JavaSchool2023 pull request #195
Opened 2023-10-08 01:34 UTC by Make-Your-Choice

… сервера

2023-10-10 05:29 UTC, markikz commented on Task9/src/main/java/yanko/client/Client.java
> +        int portNumber = 1777;
ip и порт в константу бы

2023-10-10 05:34 UTC, markikz commented on Task9/src/main/java/yanko/client/Client.java
> +            Socket socket = new Socket("127.0.0.1", portNumber);
у сокета есть автозакрытие

2023-10-10 05:36 UTC, markikz commented on Task9/src/main/java/yanko/server/SocketThread.java
> +import java.io.*;
звездочка, чтобы не схлопывалось:
![image](https://github.com/MYORGSCHOOL/JavaSchool2023/assets/32810321/26f61859-92ae-4a74-bd8f-9fc52fc14507)

2023-10-11 01:46 UTC, IrinaKorsun requested changes

2023-10-11 01:46 UTC, IrinaKorsun commented on Task9/src/main/java/yanko/server/SocketThread.java
> +    public synchronized void authorizeUser(InputStreamReader reader, OutputStreamWriter writer) throws IOException {
Подскажи, какой тут практический смысл от synchronised?
У тебя на каждого клиента будет выделен экземпляр этого класса, соответсвенно синхронизация будет this
Во все эти синхронизированные будет и так заходить только 1 поток

2023-10-12 18:23 UTC, markikz approved these changes

2023-10-13 16:13 UTC, IrinaKorsun commented on Task9/src/main/java/yanko/server/UserBase.java
> +        users.remove(name);
так, а если у нас с тобой два потока придут, один список запроси а другой удалит пользака?
Тут должна быть либо concurrent  реализация мапы, либо синхронизация какая то

2023-10-13 16:14 UTC, IrinaKorsun commented on Task9/src/main/java/yanko/server/UserBase.java
> +        users.remove(name);
проще посмотреть что есть в библиотеке java.util.concurrent  для такого случая

2023-10-14 08:02 UTC, Make-Your-Choice commented
проверки почему-то не проходят, хотя я несколько раз проект обновляла

2023-10-16 15:12 UTC, IrinaKorsun approved these changes

2023-10-16 15:12 UTC, merged