Task7 Кашуба реализовал свой аналог junit библиотеки и тесты
MYORGSCHOOL/JavaSchool2023 pull request #201
Opened 2023-10-15 05:42 UTC by 2505644

2023-10-16 15:16 UTC, IrinaKorsun requested changes

2023-10-16 15:16 UTC, IrinaKorsun commented on Task7/src/main/java/kashuba/AnnotationRunner.java
> +        if (list.size() == 2) {
Почему ?) в классе могут быть 2 тест метода) и не быть before и after

2023-10-16 15:16 UTC, IrinaKorsun commented on Task7/src/main/java/kashuba/AnnotationRunner.java
> +        List<Method> resultList = list.subList(2, list.size()).stream()
Аналогично тут не очень корректно 2 первых метода отсекать )

2023-10-17 12:54 UTC, 2505644 commented on Task7/src/main/java/kashuba/AnnotationRunner.java
> +        if (list.size() == 2) {
Список всегда изначально имеет два элемента - это beforeAll и afterAll
List<Method> list = new ArrayList<>(Arrays.asList(null, null));

2023-10-17 12:54 UTC, 2505644 commented on Task7/src/main/java/kashuba/AnnotationRunner.java
> +        List<Method> resultList = list.subList(2, list.size()).stream()
Если будут 2 тестовых метода, то кол-во элементов в списке будет 4

2023-10-18 10:57 UTC, IrinaKorsun commented on Task7/src/main/java/kashuba/AnnotationRunner.java
> +        if (list.size() == 2) {
Очень не очевидно … это еще догадываться нужно почему два null элемента добавлены изначально

2023-10-18 11:05 UTC, IrinaKorsun approved these changes

2023-10-19 04:22 UTC, IrinaKorsun approved these changes

2023-10-19 04:23 UTC, merged