Feature/sevostyanov/task1
MYORGSCHOOL/JavaSchool2023 pull request #25
Opened 2023-07-29 19:47 UTC by SevostyanovAleksandr

2023-07-30 06:17 UTC, IrinaKorsun requested changes

2023-07-30 06:17 UTC, IrinaKorsun commented on Task1/src/main/java/sevostyanov/Task1.java
> +        System.out.println("������ Sber");
ооойй это что такое?)

2023-07-30 06:17 UTC, IrinaKorsun commented on Task1/src/main/java/sevostyanov/Task1.java
> +        System.out.println("������ Sber");
Давай заменим на что нибудь другое)

2023-07-31 10:25 UTC, SevostyanovAleksandr commented on Task1/src/main/java/sevostyanov/Task1.java
> +        System.out.println("������ Sber");
эх эта кодировка, изменил кодировку на UTF - 8.

2023-07-31 15:17 UTC, merged