Task2 Проскурина Реализация класса Vector + использование в main
MYORGSCHOOL/JavaSchool2023 pull request #29
Opened 2023-07-30 09:09 UTC by OlgaProskurina

2023-07-31 15:22 UTC, IrinaKorsun requested changes

2023-07-31 15:22 UTC, IrinaKorsun commented on Task2/src/main/java/proskurina/Vector.java
> +        return y;
this.y

2023-07-31 15:22 UTC, IrinaKorsun commented on Task2/src/main/java/proskurina/Vector.java
> +        return x;
this.x

2023-07-31 15:22 UTC, IrinaKorsun commented on Task2/src/main/java/proskurina/Vector.java
> +        return z;
this.z

2023-07-31 15:22 UTC, IrinaKorsun commented on Task2/src/main/java/proskurina/Vector.java
> +    public double length() { return Math.sqrt(x*x + y*y + z*z); }
this.x. и т д) Давай везде чтобы тогда уж одинаково было

2023-07-31 15:50 UTC, markikz commented on Task2/src/main/java/proskurina/Vector.java
> +    public static Vector[] GetRandomVectors(int count) throws IllegalArgumentException{
Названия классов с заглавной буквы, а методов с маленькой

2023-07-31 15:53 UTC, markikz commented on Task2/src/main/java/proskurina/Vector.java
> +        if (count < 0)
Во всех if, for и тд желательно всегда использовать скобки { }

2023-07-31 15:57 UTC, markikz commented on Task2/src/main/java/proskurina/Vector.java
> +    public Vector(double x, double y, double z){
Перед скобкой нет пробела, чтобы поправить выравнивание кода во всем файле можно использовать сочетание клавиш Ctrl + Alt + L

2023-07-31 16:54 UTC, OlgaProskurina commented on Task2/src/main/java/proskurina/Vector.java
> +    public Vector(double x, double y, double z){
Все исправила

2023-08-01 13:53 UTC, markikz approved these changes

2023-08-01 15:01 UTC, merged