Task2 Пирязев Реализован класс Vector, проверка методов в классе Task2
MYORGSCHOOL/JavaSchool2023 pull request #30
Opened 2023-07-30 10:16 UTC by Hippoflex

2023-07-31 15:24 UTC, IrinaKorsun requested changes

2023-07-31 15:24 UTC, IrinaKorsun commented on Task1/src/main/java/piryazev/Vector.java
> +    public static Vector[] vectorsArray(int N){
параметры метода с маленькой буквы) большими только константы обозначаются)

2023-07-31 16:17 UTC, markikz commented on Task1/src/main/java/piryazev/Task2.java
> +        int N = random.nextInt(10);
Название классов с большой буквы, название полей и методов с маленькой, константы капсом + snake case

2023-07-31 16:19 UTC, markikz commented on Task1/src/main/java/piryazev/Task2.java
> +import static piryazev.Vector.*;
С точки зрения производительности, использование импорта со звездочкой на самом деле не импортирует все классы в пакете. Когда твой код компилируется, в байт-код добавляются только классы, используемые из этого пакета. Однако лучше указывать явно какие классы мы импортируем:
Явный импорт четко указывает, какие внешние классы использует текущий класс, и
если вдруг будут два класса с одинаковыми именами из разных пакетов, при использовании звездочки это может вызвать коллизию

2023-07-31 16:36 UTC, Hippoflex commented on Task1/src/main/java/piryazev/Task2.java
> +        int N = random.nextInt(10);
Изменил название параметра

2023-08-01 14:07 UTC, markikz commented on Task1/src/main/java/piryazev/Vector.java
> +
Лишняя строка

2023-08-01 14:07 UTC, markikz commented
Только метод создающий N векторов должен быть статическим. Остальные должны принадлежать объектам и использовать данные из объекта. Поэтому в сигнатуре метода останется только один параметр public double calcScalar(Vector vector2). Поправь, пожалуйста )

2023-08-01 15:37 UTC, Hippoflex commented on Task1/src/main/java/piryazev/Vector.java
> +
Удалил

2023-08-01 15:37 UTC, Hippoflex commented on Task1/src/main/java/piryazev/Vector.java
> +    public static double vectorLength(Vector vector){
Выровнял

2023-08-02 16:11 UTC, markikz commented
Все ок, только нужно схлопнуть коммиты

2023-08-02 17:34 UTC, Hippoflex commented
> Все ок, только нужно схлопнуть коммиты

Схлопнул все коммиты :)

2023-08-04 14:19 UTC, markikz approved these changes

2023-08-04 15:08 UTC, IrinaKorsun approved these changes

2023-08-04 18:40 UTC, merged