Task2 Карманчикова Класс описывающий вектор в трехмерном пространстве
MYORGSCHOOL/JavaSchool2023 pull request #34
Opened 2023-07-31 07:55 UTC by EkaterinaKarmanchikova

2023-07-31 15:37 UTC, IrinaKorsun requested changes

2023-07-31 15:37 UTC, IrinaKorsun commented on Task2/src/main/java/karmanchikova/Vector.java
> +import static java.lang.Math.*;
С точки зрения производительности, использование импорта со звездочкой на самом деле не импортирует все классы в пакете. Когда твой код компилируется, в байт-код добавляются только классы, используемые из этого пакета. Однако лучше указывать явно какие классы мы импортируем:
Явный импорт четко указывает, какие внешние классы использует текущий класс, и
если вдруг будут два класса с одинаковыми именами из разных пакетов, при использовании звездочки это может вызвать коллизию

2023-07-31 15:37 UTC, IrinaKorsun commented on Task2/src/main/java/karmanchikova/Vector.java
> +    final int x,y,z;
давай поправим code style ctrl + alt + L

2023-07-31 15:37 UTC, IrinaKorsun commented on Task2/src/main/java/karmanchikova/Vector.java
> +    final int x,y,z;
и таких однострочных вариантов написания лучше избегать

2023-07-31 15:37 UTC, IrinaKorsun commented on Task2/src/main/java/karmanchikova/Vector.java
> +    static int[][] getRandom(int N){
название параметра метода с маленькой буквы

2023-07-31 15:37 UTC, IrinaKorsun commented on Task2/src/main/java/karmanchikova/Vector.java
> +        int[][] vectors = new int[N][3];
для чего двумерный массив?

2023-07-31 16:09 UTC, markikz commented on Task2/src/main/java/karmanchikova/Vector.java
> +
Для упрощения восприятия желательно не ставить больше одной пустой строки

2023-08-01 03:32 UTC, IrinaKorsun commented on Task2/src/main/java/karmanchikova/Vector.java
> +    static int[][] getRandom(int N){
давай мы тут будем все таки одномерный массив возвращать Vectors[] vectors = new Vectors[n]

2023-08-01 14:14 UTC, markikz commented on Task1/src/main/java/karmanchikova/Task1.java
> +    public static void main(String[] args) {
нужно убрать диф по первой таске

2023-08-03 09:32 UTC, closed without merging