Task2 Савинский Вектор
MYORGSCHOOL/JavaSchool2023 pull request #63
Opened 2023-08-06 08:04 UTC by rigastalin

2023-08-06 09:52 UTC, IrinaKorsun requested changes

2023-08-06 09:52 UTC, IrinaKorsun commented on Task2/src/main/java/savinskiy/Vector.java
> +    public static Vector[] randomVectorsArray(int N) {
параметр метода с маленькой буквы

2023-08-06 12:32 UTC, rigastalin commented on Task2/src/main/java/savinskiy/Vector.java
> +    public static Vector[] randomVectorsArray(int N) {
исправил

2023-08-07 14:33 UTC, IrinaKorsun approved these changes

2023-08-07 14:33 UTC, merged