Task3 Кашуба реализовал стек, очередь и тесты к ним
MYORGSCHOOL/JavaSchool2023 pull request #67
Opened 2023-08-06 15:31 UTC by 2505644

Task3 Кашуба реализовал стек, очередь и тесты к ним

2023-08-07 12:51 UTC, markikz commented on Task3/src/main/java/kashuba/Queue.java
> +            throw new ArrayIndexOutOfBoundsException("Очередь заполнена");
по смыслу лучше подходит java.lang.IndexOutOfBoundsException (все таки это очередь а не массив) или можно создать собственные исключения

2023-08-07 12:53 UTC, markikz commented on Task3/src/main/java/kashuba/Queue.java
> +            throw new IllegalStateException("Очередь пуста");
java.lang.NoSuchElementException

2023-08-07 12:53 UTC, markikz commented on Task3/src/main/java/kashuba/Queue.java
> +public class Queue {
на класс можно тоже докинуть доку

2023-08-07 12:56 UTC, markikz commented on Task3/src/test/java/kashuba/QueueTest.java
> +    void test1() {
Несмотря на наличие displayName, в названии тестов лучше писать, что тестируется в тесте и начитать со слова test. testIllegalStateExceptionWhenTopEmptyQueue

2023-08-07 12:57 UTC, markikz commented on Task3/src/main/java/kashuba/Stack.java
> +public class Stack {
по стеку аналогичные комментарии

2023-08-13 12:24 UTC, 2505644 commented on Task3/src/main/java/kashuba/Queue.java
> +            throw new ArrayIndexOutOfBoundsException("Очередь заполнена");
+

2023-08-14 15:22 UTC, IrinaKorsun requested changes

2023-08-14 15:22 UTC, IrinaKorsun commented on Task3/src/main/java/kashuba/Stack.java
> +        this(10);
Очень тяжело будет использовать этот стек в 4 задаче, давай его делать саморасширяемым?

2023-08-14 15:23 UTC, IrinaKorsun requested changes

2023-08-14 15:23 UTC, IrinaKorsun commented on Task3/src/main/java/kashuba/Queue.java
> +        this(10);
Давай избавимся от магических чисел, выноси в константу с понятным наименованием)

2023-08-16 16:25 UTC, markikz commented on Task3/src/test/java/kashuba/QueueTest.java
> +import static org.junit.jupiter.api.Assertions.*;
звездочка в импортах

2023-08-16 16:29 UTC, markikz commented on Task3/src/test/java/kashuba/QueueTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Чтобы не схлопывались, можно в настройках задать количество для схлопывания 99 
![image](https://github.com/MYORGSCHOOL/JavaSchool2023/assets/32810321/ecab8465-ad16-471f-bf0a-072c23f6cb36)

2023-08-17 03:33 UTC, IrinaKorsun approved these changes

2023-08-17 03:33 UTC, merged