Task3 Скребков реализовал классы Queue и Stack + тесты к ним
MYORGSCHOOL/JavaSchool2023 pull request #68
Opened 2023-08-07 03:31 UTC by Sergey-Skrebkov

2023-08-07 13:02 UTC, markikz commented on Task3/src/main/java/skrebkov/Queue.java
> +        } catch (StackOverflowError e) {
Нет смысла перехватывать и пробрасывать дальше, оно и так Unchecked

2023-08-07 13:28 UTC, Sergey-Skrebkov commented on Task3/src/main/java/skrebkov/Queue.java
> +        } catch (StackOverflowError e) {
Убрал

2023-08-07 15:21 UTC, markikz commented on Task3/src/main/java/skrebkov/Queue.java
> +        } catch (StackOverflowError e) {
Сорян, за раз получилось не посмотреть, сейчас целиком чекну -)

2023-08-07 15:27 UTC, markikz commented on Task3/src/main/java/skrebkov/Stack.java
> +    private ArrayList<Object> stackArray;
Не уточнял у Иры, коллекции можно использовать? Или нужно на массиве сделать?

2023-08-07 15:31 UTC, markikz commented on Task3/src/main/java/skrebkov/Queue.java
> +    public boolean isNull() {
isEmpty более подходящее название

2023-08-07 15:32 UTC, markikz commented on Task3/src/main/java/skrebkov/Stack.java
> +public class Stack {
По стеку аналогичные комментарии

2023-08-08 06:10 UTC, Sergey-Skrebkov commented on Task3/src/main/java/skrebkov/Stack.java
> +    private ArrayList<Object> stackArray;
Спрашивал, говорила можно, но с коллекциями хардкора не хватает)

2023-08-08 17:11 UTC, markikz commented on Task3/src/main/java/skrebkov/Queue.java
> +    private final int FIRST_ELEMENT = 0;
Тут еще статик не хватает

2023-08-09 12:45 UTC, Sergey-Skrebkov commented on Task3/src/main/java/skrebkov/Queue.java
> +    private final int FIRST_ELEMENT = 0;
Добавил

2023-08-09 14:58 UTC, IrinaKorsun requested changes

2023-08-09 14:58 UTC, IrinaKorsun commented on Task3/src/main/java/skrebkov/Queue.java
> +    public void enqueue(Object object) throws StackOverflowError {
смотри, ты пишешь что метод кидает стековерфлоу, заставляя того кто методом пользуется проработать эту ситуацию
А можно ли ее проработать?
При переполнении стека все, хана всему и вся)

2023-08-09 15:02 UTC, IrinaKorsun commented on Task3/src/main/java/skrebkov/Queue.java
> +    public void enqueue(Object object) throws StackOverflowError {
метод add в коллекции тоже ничего не выкидывает

<img width="656" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/b06fd5c0-11e5-4d3d-9e13-5f24aa74a330">

2023-08-09 15:03 UTC, IrinaKorsun commented on Task3/src/main/java/skrebkov/Queue.java
> +    public void enqueue(Object object) throws StackOverflowError {
в остальном вопросов нет

2023-08-10 05:50 UTC, Sergey-Skrebkov commented on Task3/src/main/java/skrebkov/Queue.java
> +    public void enqueue(Object object) throws StackOverflowError {
😱 не дотер эксперементы после лекции по исключениям

2023-08-11 13:26 UTC, IrinaKorsun approved these changes

2023-08-11 13:26 UTC, merged