Task3 Пирязев Реализованы классы Stack и Queue и тесты для них
MYORGSCHOOL/JavaSchool2023 pull request #70
Opened 2023-08-07 13:50 UTC by Hippoflex

2023-08-07 14:43 UTC, IrinaKorsun requested changes

2023-08-07 14:43 UTC, IrinaKorsun commented on Task3/src/main/java/piryazev/Queue.java
> +    public Queue(int maxSize) {
Таким образом мы ограничиваем возможные действия того кто будет использовать наш класс, и если ему очереди не хватит то он будет вынужден создавать новую и перекладывать все из старой
Давай лучше сделаем так, чтобы очередь была саморасширяемая, и было константой задана какая то стартовая длина

2023-08-07 14:44 UTC, IrinaKorsun requested changes

2023-08-07 14:44 UTC, IrinaKorsun commented on Task3/src/main/java/piryazev/Stack.java
> +    public Stack(int maxSize) {
Аналогично)

2023-08-07 17:52 UTC, Hippoflex commented on Task3/src/main/java/piryazev/Stack.java
> +    public Stack(int maxSize) {
Добавил саморасширяемость

2023-08-08 09:28 UTC, IrinaKorsun requested changes

2023-08-08 09:28 UTC, IrinaKorsun commented on Task3/src/main/java/piryazev/Queue.java
> +        if (!isEmpty()) {
вот эта штука у меня элемент из очереди не удалила

<img width="804" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/b33f7ab0-642c-4bc4-bc38-ddb47620a711">

2023-08-08 09:29 UTC, IrinaKorsun commented on Task3/src/main/java/piryazev/Queue.java
> +        if (!isEmpty()) {
<img width="841" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/e4bb4671-be4c-40d5-bf1c-5e9f5e6a33c3">
Аналогично со стеком

2023-08-08 10:18 UTC, Hippoflex commented on Task3/src/main/java/piryazev/Queue.java
> +        if (!isEmpty()) {
Забыл занулять при удалении... Поправил :)

2023-08-09 12:00 UTC, IrinaKorsun commented on Task3/src/main/java/piryazev/Queue.java
> +    /**
по хорошему бы trim  делать периодически
<img width="1253" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/db5000eb-90b3-4983-8f4d-8f398f26bd7e">

потому что при удалении слева образуются пустые места бесконечно

2023-08-09 12:01 UTC, IrinaKorsun approved these changes

2023-08-09 12:02 UTC, merged