Task3 Проскурина Реализация классов Stack и Queue
MYORGSCHOOL/JavaSchool2023 pull request #71
Opened 2023-08-07 18:53 UTC by OlgaProskurina

2023-08-08 09:51 UTC, IrinaKorsun commented on Task3/src/main/java/proskurina/Queue.java
> +                                             : oldCapacity << 1;
а что такое oldCapacity << 1; ?

2023-08-08 09:56 UTC, IrinaKorsun requested changes

2023-08-08 09:56 UTC, IrinaKorsun commented on Task3/src/main/java/proskurina/Queue.java
> +     * Если размер равен 0, то увеличит его до STANDARD_CAPACITY.
Давай добавим методы который даст нам понимание того что сейчас есть в структурах
Чтобы методы можно было протестировать, можно в них возвращать массив обьектов которые лежат в стеке/очереди. только не просто отдавать ссылку на внутренний массив!! иначе можно будет через эту ссылку чтонибудь внутри подпортить. Это должен быть новый массив

> Ирина Кузьмина:
это должен быть обязательно НОВЫЙ масссив

2023-08-08 10:37 UTC, OlgaProskurina commented on Task3/src/main/java/proskurina/Queue.java
> +                                             : oldCapacity << 1;
увеличение размера очереди в 2 раза

2023-08-08 10:52 UTC, OlgaProskurina commented on Task3/src/main/java/proskurina/Queue.java
> +     * Если размер равен 0, то увеличит его до STANDARD_CAPACITY.
добавила toArray и toString на всякий случай

2023-08-09 12:08 UTC, IrinaKorsun requested changes

2023-08-09 12:08 UTC, IrinaKorsun commented on Task3/src/main/java/proskurina/Stack.java
> +
<img width="1237" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/a1f5cb24-0e22-464f-a262-8ac4d2372b10">

 И тут можно тримить

В остальном вопросов нет)

2023-08-09 14:31 UTC, OlgaProskurina commented on Task3/src/main/java/proskurina/Stack.java
> +
Добавила всем trim'ы

2023-08-10 04:43 UTC, IrinaKorsun approved these changes

2023-08-10 04:43 UTC, merged