Task3 Воловник Реализация Стека и Очереди, покрытие тестами
MYORGSCHOOL/JavaSchool2023 pull request #72
Opened 2023-08-08 08:03 UTC by alex65677

2023-08-08 09:57 UTC, IrinaKorsun requested changes

2023-08-08 09:57 UTC, IrinaKorsun commented on Task3/src/main/java/volovnik/Task3.java
> +    public static void main(String[] args) {
Давай добавим методы который даст нам понимание того что сейчас есть в структурах. getAll() допустим .
Чтобы методы можно было протестировать, можно в них возвращать массив обьектов которые лежат в стеке/очереди. только не просто отдавать ссылку на внутренний массив!! иначе можно будет через эту ссылку чтонибудь внутри подпортить. Это должен быть новый массив

2023-08-09 12:12 UTC, IrinaKorsun requested changes

2023-08-09 12:12 UTC, IrinaKorsun commented on Task3/src/main/java/volovnik/Queue.java
> +    public Queue(int maxQueue) {
если я правильно понимаю то мы заставляем разработчика сразу понять какой максимальный разсер стека ему нужен
К сожалению в современных реалиях точно угадать нельзя, и если я на бой выпущу стек с 100 элементами, через год он может упасть потому что нагрузка увеличится и тут будет около миллиона записей
Давай делать стек и очередь динамически расширяемыми
В идеале сделать дополнительный отдельный конструктор со стартовым обьемом. ( initial size)

2023-08-09 12:16 UTC, IrinaKorsun requested changes

2023-08-09 12:22 UTC, IrinaKorsun requested changes

2023-08-09 12:22 UTC, IrinaKorsun commented on Task3/src/main/java/volovnik/Queue.java
> +    private int objectsInQueue = 0;
Вроде размер 10 сделала, но после нескольких итераций работы с очередью все упало
![Uploading image.png…]()

2023-08-09 12:24 UTC, IrinaKorsun commented on Task3/src/main/java/volovnik/Queue.java
> +    private int objectsInQueue = 0;
такой кейс более показателен
<img width="1217" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/aed631bb-6e45-4d9e-a07b-1a3450bdc2d2">

2023-08-10 08:46 UTC, alex65677 commented on Task3/src/main/java/volovnik/Queue.java
> +    public Queue(int maxQueue) {
Сделал

2023-08-10 08:46 UTC, alex65677 commented on Task3/src/main/java/volovnik/Stack.java
> +            throw new Exception("Стек переполнен");
Сделал

2023-08-10 08:47 UTC, alex65677 commented on Task3/src/main/java/volovnik/Queue.java
> +    private int objectsInQueue = 0;
Исправил

2023-08-11 13:24 UTC, IrinaKorsun requested changes

2023-08-11 13:24 UTC, IrinaKorsun commented on Task3/src/main/java/volovnik/Queue.java
> +    private int objectsInQueue = 0;
<img width="1133" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/f78e7ec9-9a04-4787-a281-bc85385baa72">
  Чет не сошелся у меня ожидаемый ответ.. тесты на такое есть?

2023-08-12 13:03 UTC, alex65677 commented on Task3/src/main/java/volovnik/Queue.java
> +    private int objectsInQueue = 0;
Исправил

2023-08-14 15:26 UTC, IrinaKorsun approved these changes

2023-08-14 15:26 UTC, IrinaKorsun commented on Task3/src/main/java/volovnik/Queue.java
> +    private int queueStart = 0;
хорошо бы еще делать trimtosize
<img width="1126" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/b4528b79-0ee8-4b5a-a861-4dbabde0d3b0">

Давай эту мысль просто оставим так сказать на будущее

2023-08-14 15:28 UTC, merged