Task3. Grankin. Стек, очередь и теесты к ним.
MYORGSCHOOL/JavaSchool2023 pull request #75
Opened 2023-08-09 14:28 UTC by AlexGr5

Попытка №1

2023-08-09 17:23 UTC, markikz commented on Task3/src/main/java/grankin/MyQueue.java
> +    private Object[] array;
Нужно добавить final, инициализируется только один раз в конструкторе

2023-08-09 17:24 UTC, markikz commented on Task3/src/main/java/grankin/MyQueue.java
> +    private int maxSize;
maxSize тоже нужно сделать final

2023-08-09 17:30 UTC, markikz commented on Task3/src/main/java/grankin/MyQueue.java
> +    MyQueue(int maxSize) {
не хватает public, без модификатора (package-private) конструктор будет доступен только в том же пакете

2023-08-09 17:42 UTC, markikz commented on Task3/src/test/java/grankin/MyQueueTest.java
> +    public void enqueueTestUdachno(){
Было бы не плохо добавить аннотацию displayName и в ней написать, что делает тест. Названия тестов нужно начитать со слова test. testSuccessEnqueueThreeElements

2023-08-09 17:45 UTC, markikz commented on Task3/src/test/java/grankin/MyQueueTest.java
> +    public void enqueueTestNeUdachno(){
testEnqueueElementToFullQueue. Еще стоит проверить, что результат добавления в полную очередь -1

2023-08-09 17:48 UTC, markikz commented on Task3/src/test/java/grankin/MyQueueTest.java
> +    public void enqueueTestNeUdachno(){
Увидел, что дальше есть такой тест кейс -) Разбивать на более маленькие тесты даже лучше )

2023-08-09 17:55 UTC, markikz commented on Task3/src/main/java/grankin/MyStack.java
> +public class MyStack {
По стеку аналогичные комментарии

2023-08-09 17:57 UTC, markikz commented on Task3/src/test/java/grankin/MyQueueTest.java
> +    public void dequeueTestUdachno(){
testResultWhenEnqueueElementToFullQueue

2023-08-09 17:58 UTC, markikz commented on Task3/src/main/java/grankin/MyStack.java
> +    public Object pop(){
ctrl + alt + l чтобы поправить выравнивание

2023-08-14 15:33 UTC, IrinaKorsun requested changes

2023-08-14 15:33 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyQueue.java
> +        array = new Object[maxSize];
тогда уж наверное this.array this.currentSize и т д

2023-08-14 15:33 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyQueue.java
> +            else{
и тут нужно соблюсти code style alt + ctrl + L

2023-08-14 15:33 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyQueue.java
> +     * Получить начальный индекс очереди
мы же тут не индекс получаем, а обьект?
И вроде как метод должен немного иначе называться

2023-08-14 15:33 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyStack.java
> +                result = array[currentSize];
this.array

так лучше читается, сразу можно понять мы к полям класса обращаемся или такую переменную в методе надо искать где то глазами

2023-08-14 15:33 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyStack.java
> +                //return array[currentSize--];
мертвый код?

2023-08-14 15:33 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyStack.java
> +                //return array[currentSize];
тоже мертвый код?

2023-08-14 15:34 UTC, IrinaKorsun requested changes

2023-08-14 15:34 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyStack.java
> +    public MyStack(int maxSize) {
давай делать стек саморасширяемым, иначе им тяжело будет пользоваться в 4 задаче

2023-08-18 15:01 UTC, AlexGr5 commented on Task3/src/main/java/grankin/MyStack.java
> +    public MyStack(int maxSize) {
Вроде всё исправил по 3-му заданию, остальные Pull reqests (4 и 5) удалил, остался пока только этот, но у него какой-то крестик красный появился, а обычно зеленые галочки везде. Это моя ошибка или это не от меня зависит?

2023-08-20 11:19 UTC, AlexGr5 commented on Task3/src/main/java/grankin/MyStack.java
> +    public MyStack(int maxSize) {
Крестика больше нет, всё хорошо. Весь проект полностью работает.

2023-08-20 11:42 UTC, markikz commented on Task3/src/main/java/grankin/MyStack.java
> +    public void AddCapacity() {
названия методов с маленькой буквы

2023-08-20 11:42 UTC, markikz commented on Task3/src/main/java/grankin/MyQueue.java
> +public class MyQueue {
название класса нужно поправить

2023-08-20 11:43 UTC, markikz commented on Task3/src/main/java/grankin/MyQueue.java
> +
лишняя пустая строка

2023-08-22 09:56 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyQueue.java
> +public class MyQueue {
Еще актуальный коммент

2023-08-22 09:56 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyQueue.java
> +
тоже актуальный

2023-08-22 09:57 UTC, IrinaKorsun requested changes

2023-08-22 09:57 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyStack.java
> +    public void addCapacity() {
этот метод не должен быть публичный

2023-08-23 08:55 UTC, IrinaKorsun requested changes
Посмотри еще пожалуйста комментарии, остались актуальные

2023-08-23 08:59 UTC, IrinaKorsun approved these changes

2023-08-23 09:01 UTC, merged