Task4 Гроссу Реализация класса RollbackStringBuilder и класса тестов …
MYORGSCHOOL/JavaSchool2023 pull request #79
Opened 2023-08-11 09:56 UTC by GrossuEvgenia

…к нему + редактирование класса Stack для успешной работы с ним

2023-08-12 08:18 UTC, IrinaKorsun requested changes

2023-08-12 08:18 UTC, IrinaKorsun commented on Task3/src/main/java/grossu/Stack.java
> +        int newCapacity = stackArray.length+(stackArray.length>>1);
давай отформатируем код alt + ctrl + L

2023-08-12 08:19 UTC, markikz commented on Task4/src/main/java/grossu/RollbackStringBuilder.java
> +        Action action = new Action() {
Интерфейсы с одним методом можно имплиментить лямбдой
![image](https://github.com/MYORGSCHOOL/JavaSchool2023/assets/32810321/fb760ac7-49a7-4e44-8de6-9a71beee4e40)

2023-08-12 08:22 UTC, IrinaKorsun requested changes

2023-08-12 08:22 UTC, IrinaKorsun commented on Task3/src/test/java/grossu/StackTest.java
>      void testGetTrowPushWhenStackIsFull() {
это наверное уже не GetTrowPush? название актуально?

2023-08-12 08:22 UTC, IrinaKorsun commented on Task4/src/main/java/grossu/RollbackException.java
> +public class RollbackException extends RuntimeException{
тоже нужно отформатировать код

2023-08-12 08:22 UTC, IrinaKorsun commented on Task4/src/main/java/grossu/RollbackStringBuilder.java
> +        Action action = new Action() {
Пока не изучили еще это)

2023-08-12 08:38 UTC, GrossuEvgenia commented on Task4/src/main/java/grossu/RollbackException.java
> +public class RollbackException extends RuntimeException{
Исправила замечания.

2023-08-13 07:13 UTC, markikz approved these changes

2023-08-13 15:22 UTC, IrinaKorsun approved these changes

2023-08-13 15:22 UTC, merged