Task3 Малахова Реализованы классы Stack и Queue и тесты к ним
MYORGSCHOOL/JavaSchool2023 pull request #81
Opened 2023-08-11 11:18 UTC by Ulyana-Malakhova

2023-08-12 08:23 UTC, IrinaKorsun requested changes

2023-08-12 08:23 UTC, IrinaKorsun commented on Task3/src/main/java/malakhova/Queue.java
> +    private int SIZE;
если это не константа то не нужно название делать заглавными)

2023-08-12 08:23 UTC, IrinaKorsun commented on Task3/src/main/java/malakhova/Queue.java
> +        COUNTER = 0;
this.

2023-08-12 08:24 UTC, IrinaKorsun requested changes

2023-08-12 08:24 UTC, IrinaKorsun commented on Task3/src/main/java/malakhova/Stack.java
> +    public Stack(int s) {
Давай переделаем структуры так чтобы они были расширяемые, иначе тяжело потом будет их использовать для задачи 4

2023-08-12 08:31 UTC, markikz commented on Task3/src/main/java/malakhova/Queue.java
> +public class Queue {
Было бы не плохо на класс тоже доку добавить

2023-08-12 08:33 UTC, markikz commented on Task3/src/main/java/malakhova/Queue.java
> +    private Object[] queue = new Object[10];
нужно сделать final и инициализировать в конструкторе в зависимости от переданной длины

2023-08-12 08:36 UTC, markikz commented on Task3/src/main/java/malakhova/Queue.java
> +    private int SIZE;
кажется что maxSize лучше подойдет, и тоже нужно сделать final

2023-08-12 08:41 UTC, markikz commented on Task3/src/main/java/malakhova/Queue.java
> +    private Object[] queue = new Object[10];
не стоит называть поле также как класс в котором оно находится, потому что геттер будет называться getQueue, а возвращать другой тип

2023-08-12 08:43 UTC, markikz commented on Task3/src/test/java/malakhova/Task3TestQueue.java
> +    public void enqueueTest() {
Название тестов лучше начитать со слова test. И несмотря на наличие displayName писать в названии, что происходит в тесте. testSuccessEnqueueElementsToQueue (тестирую успешное добавление элементов)

2023-08-12 08:45 UTC, markikz commented on Task3/src/test/java/malakhova/Task3TestQueue.java
> +public class Task3TestQueue {
Название класса с тестами должно быть по шаблону `Тестируемый класс`Test (QueueTest)

2023-08-14 19:37 UTC, Ulyana-Malakhova commented on Task3/src/main/java/malakhova/Queue.java
> +    private int SIZE;
Изменила названия

2023-08-14 19:38 UTC, Ulyana-Malakhova commented on Task3/src/main/java/malakhova/Queue.java
> +        COUNTER = 0;
Добавила this в конструкторы

2023-08-14 19:40 UTC, Ulyana-Malakhova commented on Task3/src/main/java/malakhova/Stack.java
> +    public Stack(int s) {
Добавила в метод push проверку заполнен ли массив и если заполнен увеличиваю его длину

2023-08-14 19:40 UTC, Ulyana-Malakhova commented on Task3/src/main/java/malakhova/Queue.java
> +public class Queue {
Добавила

2023-08-14 19:42 UTC, Ulyana-Malakhova commented on Task3/src/main/java/malakhova/Queue.java
> +    private Object[] queue = new Object[10];
Поменяла название массива и его инициализацию, сделала его final

2023-08-14 19:42 UTC, Ulyana-Malakhova commented on Task3/src/main/java/malakhova/Queue.java
> +    private int SIZE;
Исправила

2023-08-14 19:43 UTC, Ulyana-Malakhova commented on Task3/src/test/java/malakhova/Task3TestQueue.java
> +    public void enqueueTest() {
Поменяла названия

2023-08-14 19:43 UTC, Ulyana-Malakhova commented on Task3/src/test/java/malakhova/Task3TestQueue.java
> +public class Task3TestQueue {
Изменила названия классов с тестами

2023-08-16 16:39 UTC, markikz commented on Task3/src/main/java/malakhova/Stack.java
> +        if (arrayStack[start] == null) {
можно просто return arrayStack[start] == null, тоже самое получится ))

2023-08-16 16:41 UTC, markikz commented on Task3/src/main/java/malakhova/Stack.java
> +        if (counter < maxSize) {
эта проверка еще актуальна? если правильно понял, если counter == maxSize, то размер стека увеличивается?

2023-08-16 16:43 UTC, markikz commented on Task3/src/main/java/malakhova/Stack.java
> +        } else {
В таких случаях лучше не писать else, чтобы меньше вложенности было, а просто дальше писать основной код. Так чутка удобнее в больших функциях, где ифов много

2023-08-16 16:45 UTC, markikz commented on Task3/src/main/java/malakhova/Stack.java
> +    public Object pop() {
public Object pop() {
        if (arrayStack[start] == null) {
            throw new IllegalArgumentException();
        }
        Object a = arrayStack[counter - 1];
        counter--;
        arrayStack[counter] = null;
        return a;
}

2023-08-16 16:47 UTC, markikz commented on Task3/src/main/java/malakhova/Stack.java
> +        if (start != counter) {
Тут тоже можно переделать без else, сначала if(start == counter){ошибка}, а дальше основной код без else

2023-08-16 16:55 UTC, markikz commented on Task3/src/test/java/malakhova/StackTest.java
> +    public void testSuccessTopOfTheStack() {
Юнит тесты желательно делать на какой то конкретный случай, поэтому тут можно просто создать пустую очередь и проверить, что на ней метод top() выкидывает исключение.

2023-08-20 11:48 UTC, markikz commented
Нужно подтянуть актуальную ветку мейн и ребейзвуться (в старой тесты сломаны). В остальном все ок

2023-08-20 11:49 UTC, markikz submitted a review, later dismissed

2023-08-21 11:38 UTC, IrinaKorsun requested changes

2023-08-21 11:38 UTC, IrinaKorsun commented on Task3/src/main/java/malakhova/Stack.java
> +            maxSize += 5;
давай избавимся от магических цифр, это ведь то на сколько стек увеличивается?
Давай константу под это заведем)
И увеличение стека можно в отдельный приватный метод вынести

Больше вопросов нет

2023-08-21 11:57 UTC, Ulyana-Malakhova commented on Task3/src/main/java/malakhova/Stack.java
> +            maxSize += 5;
Исправила

2023-08-22 09:54 UTC, IrinaKorsun requested changes

2023-08-22 09:54 UTC, IrinaKorsun commented on Task3/src/main/java/malakhova/Stack.java
> +    private void increase() {
приватный методы вниз класса

2023-08-22 12:41 UTC, Ulyana-Malakhova commented on Task3/src/main/java/malakhova/Stack.java
> +    private void increase() {
Перенесла метод вниз класса

2023-08-22 18:19 UTC, markikz approved these changes

2023-08-23 08:53 UTC, IrinaKorsun approved these changes

2023-08-23 08:54 UTC, merged