Feature/sevostyanov/task3
MYORGSCHOOL/JavaSchool2023 pull request #84
Opened 2023-08-13 13:09 UTC by SevostyanovAleksandr

2023-08-13 15:26 UTC, IrinaKorsun requested changes

2023-08-13 15:26 UTC, IrinaKorsun commented on Task2/src/main/java/sevostyanov/Task2.java
> +        System.out.println("Длина вектора = " + vectorOne.vectorLength());
Кажется стоит перейти на английский)

2023-08-13 15:26 UTC, IrinaKorsun commented on Task2/src/main/java/sevostyanov/Vector.java
> +    int x;
private final

2023-08-13 15:26 UTC, IrinaKorsun commented on Task3/src/main/java/sevostyanov/Queue.java
> +     * Текущий размер очереди
Может что то с кодировкой? можно попробовать utf8

2023-08-13 15:26 UTC, IrinaKorsun commented on Task2/src/main/java/sevostyanov/Vector.java
> +            arrVector[i] = new Vector(random.nextInt(312), random.nextInt(312), random.nextInt(312));
давай избегать магических чисел.. 312 стоит вынести в константу с понятным названием

2023-08-13 15:26 UTC, IrinaKorsun commented on Task3/src/main/java/sevostyanov/Queue.java
> +    public Queue(int maxSize) {
Давай делать очередь саморасширяемой

2023-08-13 15:26 UTC, IrinaKorsun commented on Task3/src/main/java/sevostyanov/Stack.java
> +    public Stack(int s) {
и стек саморасширяемый, он понадобится в 4 задаче, и если он будет с ограниченным размером то им будет сложно пользоваться

2023-08-14 10:48 UTC, SevostyanovAleksandr commented on Task2/src/main/java/sevostyanov/Vector.java
> +    int x;
исправил

2023-08-14 17:20 UTC, markikz commented on Task2/src/main/java/sevostyanov/Task2.java
> +        System.out.println("Длина вектора = " + vectorOne.vectorLength());
Можно попробовать кодировку поменять 
![image](https://github.com/MYORGSCHOOL/JavaSchool2023/assets/32810321/a9492ab9-c1ed-40f0-a3ae-94e980d2d312)

2023-08-14 17:22 UTC, markikz commented
Название ПР по шаблону Task`номер` `Фамилия` `Что сделано`

2023-08-27 15:04 UTC, IrinaKorsun requested changes

2023-08-27 15:04 UTC, IrinaKorsun commented on Task2/src/main/java/sevostyanov/Task2.java
> +    public static void main(String[] args) {
давай на таск 2 отдельный пр сделаем?

2023-08-28 07:46 UTC, SevostyanovAleksandr commented on Task2/src/main/java/sevostyanov/Task2.java
> +    public static void main(String[] args) {
Совсем запутался. Ветка с задачей task 2, уже смержина. Мне необходимо создать новую ветку, таск2, добавить в нее изменения, закомитеть, отправить в удаленный репозиторий и прожать ПР?

2023-08-30 01:51 UTC, IrinaKorsun requested changes

2023-08-30 01:51 UTC, IrinaKorsun commented on Task2/src/main/java/sevostyanov/Task2.java
> +    public static void main(String[] args) {
<img width="677" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/cad6d46b-4ccd-40f1-ad87-79a50487ceca">
у тебя вот тут не должно просто быть изменений по task2)

2023-10-13 16:15 UTC, IrinaKorsun commented
Закрываю так как долго висит без реакции

2023-10-13 16:15 UTC, closed without merging