Task4 Позднякова Создание класса RollbackStringBuilder и тестов к нему.
MYORGSCHOOL/JavaSchool2023 pull request #85
Opened 2023-08-13 15:28 UTC by Pozdnyakova-Elizaveta

Редактирование предыдущего задания для расширяемого стека и введения исключений

2023-08-14 15:44 UTC, IrinaKorsun requested changes

2023-08-14 15:49 UTC, IrinaKorsun requested changes

2023-08-14 15:49 UTC, IrinaKorsun commented on Task3/src/main/java/pozdnyakova/Stack.java
>   */
<img width="1069" alt="image" src="https://github.com/MYORGSCHOOL/JavaSchool2023/assets/22653719/a129f571-d677-4d22-9bc9-19628b899320">
Оййй

2023-08-14 15:49 UTC, IrinaKorsun commented on Task3/src/main/java/pozdnyakova/CircularQueue.java
> +            throw new IllegalStateException();
Давай может какой нибудь Message сюда напишем?

2023-08-14 15:49 UTC, IrinaKorsun commented on Task4/src/main/java/pozdnyakova/RollbackStringBuilder.java
> +    /**
тут вопросов нет) Если стек заработает то и этот класс заработает:)

2023-08-15 04:25 UTC, Pozdnyakova-Elizaveta commented on Task3/src/main/java/pozdnyakova/Stack.java
>  public class Stack {
Исправила метод push

2023-08-15 04:26 UTC, Pozdnyakova-Elizaveta commented on Task3/src/main/java/pozdnyakova/Stack.java
>   */
Исправила метод push и отредактировала getAll, чтобы пустые элемента не выводились

2023-08-15 04:27 UTC, Pozdnyakova-Elizaveta commented on Task3/src/main/java/pozdnyakova/CircularQueue.java
> +            throw new IllegalStateException();
Добавила Message и проверила его вывод в Task3

2023-08-17 15:08 UTC, IrinaKorsun commented on Task4/src/main/java/pozdnyakova/RollbackStringBuilder.java
> +
Давай лишние строки уберем)

2023-08-17 15:09 UTC, merged