Feature/grankin/task4
MYORGSCHOOL/JavaSchool2023 pull request #87
Opened 2023-08-14 09:31 UTC by AlexGr5

RollbackStringBuilder на основе своего стека.

2023-08-14 15:56 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyStack.java
> +        if (array != null){
у тебя же по идее никогда такое не будет что array == null

2023-08-14 15:57 UTC, IrinaKorsun requested changes

2023-08-14 15:57 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyStack.java
> +        if (array != null){
Давай еще ctrl + alt + L пройдемся по всем файлам

2023-08-14 15:57 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyStack.java
> +    public MyStack(int maxSize) {
Давай сделаем стек саморасширяемым? а то в stringbuilder таким сложно будет пользоваться

2023-08-14 16:01 UTC, IrinaKorsun requested changes

2023-08-14 16:02 UTC, IrinaKorsun requested changes

2023-08-14 16:05 UTC, IrinaKorsun commented on Task3/src/main/java/grankin/MyStack.java
> +    private final Object[] array;
Посмотри пожалуйста комментарий с прошлого пр тоже. нужно теперь как то понять, в какой ветке смотреть стек и очередь

2023-08-15 10:13 UTC, AlexGr5 commented on Task3/src/main/java/grankin/MyStack.java
> +    private final Object[] array;
В ветке с 3-им заданием я исправляю 3-е задание, там всё хорошо. А как сюда (в 4-ое задание) попал комтит с 3-им я не знаю, и как его удалить, я тоже не знаю, потому что он тут не нужен. Надеюсь, что ничего страшного не случится)

2023-08-18 14:57 UTC, closed without merging

2023-08-18 14:57 UTC, AlexGr5 commented
Не работает