Task3 Бабаджанов Реализовать стэк и очередь, написать тесты к ним
MYORGSCHOOL/JavaSchool2023 pull request #90
Opened 2023-08-14 17:15 UTC by bimaister

2023-08-14 17:23 UTC, markikz commented on Task3/src/main/java/babadzhanov/Queue.java
> +public class Queue {
На класс дока тоже будет не лишней

2023-08-14 17:25 UTC, markikz commented on Task3/src/main/java/babadzhanov/Stack.java
> +            throw new IndexOutOfBoundsException("Достигнут максимальный размер стэка");
Чтобы было проще делать 4 здание, нужен расширяемый стек

2023-08-14 17:27 UTC, markikz commented on Task3/src/test/java/babadzhanov/QueueTest.java
> +    void queueIsEmptyTest() {
Названия тестов принято начитать со слова test (testIsEmpty())

2023-08-14 17:27 UTC, markikz commented on Task3/src/test/java/babadzhanov/QueueTest.java
> +    void queueEnqueueTest() {
testSuccessEnqueueOneElement

2023-08-17 20:06 UTC, bimaister commented on Task3/src/main/java/babadzhanov/Queue.java
> +public class Queue {
ок, добавил

2023-08-17 20:11 UTC, bimaister commented on Task3/src/test/java/babadzhanov/QueueTest.java
> +    void queueIsEmptyTest() {
добавил смысловой нагрузки для названия тестовых методов

2023-08-17 20:11 UTC, bimaister commented on Task3/src/test/java/babadzhanov/QueueTest.java
> +    }
ага добавил для очереди и стэка + тест на расширение стэка)

2023-08-19 14:09 UTC, IrinaKorsun requested changes

2023-08-19 14:09 UTC, IrinaKorsun commented on Task3/src/main/java/babadzhanov/Stack.java
> +        if (isEmpty()) {
но у тебя элемент ведь не удаляется по итогу?

2023-08-20 09:17 UTC, bimaister commented on Task3/src/main/java/babadzhanov/Stack.java
> +        if (isEmpty()) {
ой) поправил

2023-08-20 11:57 UTC, markikz commented on Task3/src/main/java/babadzhanov/Queue.java
> +        } else {
тут можно продолжить без else, чтобы меньше вложенности было

2023-08-21 09:50 UTC, bimaister commented on Task3/src/main/java/babadzhanov/Queue.java
> +        } else {
ага, убрал везде

2023-08-21 11:31 UTC, IrinaKorsun approved these changes

2023-08-21 11:33 UTC, merged