Task4 Скребков добавил классы RollbackStringBuilder + тесты
MYORGSCHOOL/JavaSchool2023 pull request #91
Opened 2023-08-15 13:28 UTC by Sergey-Skrebkov

2023-08-16 17:20 UTC, markikz commented on Task4/src/main/java/skrebkov/RollbackStringBuilder.java
> +        stringBuilder = new StringBuilder();
нужно добавить this

2023-08-16 17:21 UTC, markikz commented on Task4/src/main/java/skrebkov/RollbackStringBuilderException.java
> +public class RollbackStringBuilderException extends RuntimeException{
перед скобкой нет пробела crt + atl + L

2023-08-19 14:09 UTC, IrinaKorsun requested changes

2023-08-19 14:09 UTC, IrinaKorsun commented on Task4/src/main/java/skrebkov/RollbackStringBuilder.java
> +        rollbackSteps = new Stack();
this. ))

2023-08-19 14:09 UTC, IrinaKorsun commented on Task4/src/main/java/skrebkov/RollbackStringBuilder.java
> +        rollbackSteps = new Stack();
this.

2023-08-19 14:09 UTC, IrinaKorsun commented on Task4/src/main/java/skrebkov/RollbackStringBuilder.java
> +        stringBuilder.insert(offset, str);
this.

2023-08-19 14:10 UTC, IrinaKorsun requested changes

2023-08-19 14:10 UTC, IrinaKorsun commented on Task4/src/main/java/skrebkov/RollbackStringBuilder.java
> +        rollbackSteps.push(new Rollback() {
this. и т д

2023-08-20 12:00 UTC, markikz approved these changes

2023-08-21 11:28 UTC, IrinaKorsun approved these changes

2023-08-21 11:28 UTC, merged