Task5 Гроссу Реализация интерфейса Dictionary и его реализации Dictio…
MYORGSCHOOL/JavaSchool2023 pull request #93
Opened 2023-08-17 06:52 UTC by GrossuEvgenia

…naryImpl, а также касса с тестами DictionaryTest

2023-08-17 15:15 UTC, IrinaKorsun requested changes

2023-08-17 15:15 UTC, IrinaKorsun commented on Task5/src/main/java/grossu/Dictionary.java
> +    void insert(G element);
Javadoc бы)

2023-08-17 15:15 UTC, IrinaKorsun commented on Task5/src/main/java/grossu/DictionaryImpl.java
> +            Random rand = new Random();
кажется что можно это вынести наверх) в поле класса) можно даже в статическое)
Чтобы каждый раз рандом обьект не создавать

2023-08-17 15:15 UTC, IrinaKorsun commented on Task5/src/main/java/grossu/Dictionary.java
> +    void insert(G element);
Вижу что есть в имплементации.. можно в интерфейсе просто краткий сделать

2023-08-17 15:16 UTC, IrinaKorsun commented
В остальном все ок)

2023-08-17 15:56 UTC, GrossuEvgenia commented on Task5/src/main/java/grossu/Dictionary.java
> +    void insert(G element);
замечания исправила

2023-08-19 14:11 UTC, IrinaKorsun approved these changes

2023-08-19 14:11 UTC, merged