Task5 Проскурина Интерфейс Dictionary и его имплементация
MYORGSCHOOL/JavaSchool2023 pull request #94
Opened 2023-08-17 07:35 UTC by OlgaProskurina

2023-08-17 15:20 UTC, IrinaKorsun requested changes

2023-08-17 15:20 UTC, IrinaKorsun commented on Task5/src/main/java/proskurina/DictionaryImpl.java
> +        hashMap = new HashMap<>(initialCapacity);
все таки предлагаю везде писать this.
Так проще читать, сразу есть понимание что это поле класса а не переменная внутри метода)

2023-08-17 15:20 UTC, IrinaKorsun commented on Task5/src/main/java/proskurina/DictionaryImpl.java
> +        removeFromArray(removeIndex);
у нас метод назавается  "удалить из массива" а внутри у него еще какие то манипуляции с мапой)
Давай манипуляции с мапой оттуда вытащим, и просто пониже тут например сделаем, чтобы название метода совпадало с тем что он делает

2023-08-17 15:21 UTC, IrinaKorsun commented on Task5/src/main/java/proskurina/DictionaryImpl.java
> +        if (index != array.size() - 1){
еще alt+ctrl +l не хватает

2023-08-18 06:14 UTC, OlgaProskurina commented on Task5/src/main/java/proskurina/DictionaryImpl.java
> +        removeFromArray(removeIndex);
Я  сделала немного по-другому 
```java
final int lastIndex = this.array.size() - 1;
// Если удаляется не последний элемент из array
if (removeIndex != lastIndex) {
    replaceByLastElement(removeIndex);
    // Обновляем индекс последнего элемента после перестановки
    this.hashMap.replace(this.array.get(lastIndex), removeIndex);
}
removeLastFromArray();
``` 
Просто чтобы ничего не менять местами в массиве и обновлять индексы в мапе, если удаляется последний. Если вышло не очень - поменяю

2023-08-18 06:15 UTC, OlgaProskurina commented on Task5/src/main/java/proskurina/DictionaryImpl.java
> +        hashMap = new HashMap<>(initialCapacity);
Добавила везде this

2023-08-19 14:13 UTC, IrinaKorsun approved these changes

2023-08-19 14:13 UTC, merged