Task4 Пирязев Реализован класс RollbackStringBuilder, а также покрыт тестами
MYORGSCHOOL/JavaSchool2023 pull request #96
Opened 2023-08-17 14:28 UTC by Hippoflex

2023-08-19 14:16 UTC, IrinaKorsun requested changes

2023-08-19 14:16 UTC, IrinaKorsun commented on Task4/src/main/java/piryazev/RollbackStringBuilder.java
> +        stack.push(action);
давай тогда везде при обращении к полям класса добавим this. )

2023-08-19 14:17 UTC, IrinaKorsun commented on Task4/src/main/java/piryazev/RollbackStringBuilder.java
> +        stack.push(action);
в остальном вопросов нет

2023-08-20 10:00 UTC, Hippoflex commented on Task4/src/main/java/piryazev/RollbackStringBuilder.java
> +        stack.push(action);
Поправил

2023-08-20 12:02 UTC, markikz approved these changes

2023-08-21 11:26 UTC, IrinaKorsun approved these changes

2023-08-21 11:26 UTC, merged