Task5 Янько Добавлены интерфейс и реализация словаря с тестами
MYORGSCHOOL/JavaSchool2023 pull request #97
Opened 2023-08-18 08:30 UTC by Make-Your-Choice

2023-08-19 14:25 UTC, IrinaKorsun requested changes

2023-08-19 14:25 UTC, IrinaKorsun commented on Task5/src/main/java/yanko/Dictionary.java
> + * интерыейс словаря
интерыейс ?

2023-08-19 14:25 UTC, IrinaKorsun commented on Task5/src/main/java/yanko/DictionaryImpl.java
> +            if(this.consist(e)) {
вот тут this.consist можно this не писать, а вот this.list тут да

2023-08-19 14:25 UTC, IrinaKorsun commented on Task5/src/main/java/yanko/DictionaryImpl.java
> +        if(!list.isEmpty() && !hashMap.isEmpty()) {
this.hashmap

при обращении к полям класса лучше писать, а то так непонятно, толи это название переменной толи параметр метода толи поле класса

2023-08-19 14:25 UTC, IrinaKorsun commented on Task5/src/main/java/yanko/DictionaryImpl.java
> +        swap(index);
У тебя метод называется swap() да вот только его название не соответствует действительности, он еще какую то логику делает

2023-08-19 14:25 UTC, IrinaKorsun commented on Task5/src/main/java/yanko/Task5.java
> +        dictionary.insert("ccccc");*/
мертвый код?

2023-08-19 14:25 UTC, IrinaKorsun commented on Task5/src/test/java/yanko/DictionaryImplTest.java
> +            //System.out.println(end - start);
мертвый код?

2023-08-19 14:25 UTC, IrinaKorsun commented on Task5/src/test/java/yanko/DictionaryImplTest.java
> +            dictionary.insert(i);
может эту вставку вынести в отдельный метод?

2023-08-19 14:25 UTC, IrinaKorsun commented on Task5/src/test/java/yanko/DictionaryImplTest.java
> +            //System.out.println(end - start);
мертвый код

2023-08-19 14:25 UTC, IrinaKorsun commented on Task5/src/test/java/yanko/DictionaryImplTest.java
> +            //System.out.println(end - start);
мертвый код

2023-08-19 14:25 UTC, IrinaKorsun commented on Task5/src/test/java/yanko/DictionaryImplTest.java
> +        long testVal = 1_000_000_000;
не понимаю почему именно такое число

2023-08-19 14:36 UTC, Make-Your-Choice commented on Task5/src/main/java/yanko/DictionaryImpl.java
> +        swap(index);
не совсем понимаю, метод swap не выполняет никакой дополнительной логики - там только меняются местами элементы

2023-08-19 14:45 UTC, Make-Your-Choice commented on Task5/src/test/java/yanko/DictionaryImplTest.java
> +        long testVal = 1_000_000_000;
я ориентировалась на то, что каждый метод должен отрабатывать менее, чем за секунду, что в наносекундах и будет 1000000000

2023-08-21 11:24 UTC, IrinaKorsun commented on Task5/src/main/java/yanko/DictionaryImpl.java
> +        swap(index);
this.hashMap.put(element1, this.list.size() - 1);
        this.hashMap.put(element2, index);

Вот именно, он должен только менять местами элементы в массиве,
а так он еще в мапу лезет. можно назвать swapInList

2023-08-21 11:25 UTC, IrinaKorsun requested changes

2023-08-21 11:25 UTC, IrinaKorsun commented on Task5/src/test/java/yanko/DictionaryImplTest.java
> +        long testVal = 1_000_000_000;
давай тогда понятное наименование сделаем 
вынесем в константы
Можно также еще магические числа поубирать в тестах типа 500

2023-08-22 09:53 UTC, IrinaKorsun requested changes

2023-08-22 09:53 UTC, IrinaKorsun commented on Task5/src/main/java/yanko/DictionaryImpl.java
> +    private void swapInList(int index) {
Метод называется swapInList но почему то лезет в мапу, может тогда два метода сделать? один для листа, один для мапы?

2023-08-23 09:23 UTC, IrinaKorsun approved these changes

2023-08-23 09:23 UTC, merged